// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for
/// [BatchProcessDocuments][google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments].
///
/// [google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]: <doc:DocumentProcessorServiceClient/batchProcessDocuments(request:options:)>
public struct BatchProcessRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of
  /// [Processor][google.cloud.documentai.v1.Processor] or
  /// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion].
  /// Format: `projects/{project}/locations/{location}/processors/{processor}`,
  /// or
  /// `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`
  ///
  /// [google.cloud.documentai.v1.Processor]: <doc:Processor>
  /// [google.cloud.documentai.v1.ProcessorVersion]: <doc:ProcessorVersion>
  public var name: Swift.String = Swift.String()

  /// The input documents for the
  /// [BatchProcessDocuments][google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]
  /// method.
  ///
  /// [google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]: <doc:DocumentProcessorServiceClient/batchProcessDocuments(request:options:)>
  public var inputDocuments: BatchDocumentsInputConfig? = nil

  /// The output configuration for the
  /// [BatchProcessDocuments][google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]
  /// method.
  ///
  /// [google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]: <doc:DocumentProcessorServiceClient/batchProcessDocuments(request:options:)>
  public var documentOutputConfig: DocumentOutputConfig? = nil

  /// Whether human review should be skipped for this request. Default to
  /// `false`.
  public var skipHumanReview: Swift.Bool = Swift.Bool()

  /// Inference-time options for the process API
  public var processOptions: ProcessOptions? = nil

  /// Optional. The labels with user-defined metadata for the request.
  ///
  /// Label keys and values can be no longer than 63 characters
  /// (Unicode codepoints) and can only contain lowercase letters, numeric
  /// characters, underscores, and dashes. International characters are allowed.
  /// Label values are optional. Label keys must start with a letter.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchProcessRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchProcessRequest().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let inputDocuments = CodingKeys(stringValue: "inputDocuments")
    static let documentOutputConfig = CodingKeys(stringValue: "documentOutputConfig")
    static let skipHumanReview = CodingKeys(stringValue: "skipHumanReview")
    static let processOptions = CodingKeys(stringValue: "processOptions")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "inputDocuments",
      "documentOutputConfig",
      "skipHumanReview",
      "processOptions",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.inputDocuments = try container.decodeIfPresent(
      BatchDocumentsInputConfig.self, forKey: .inputDocuments)
    self.documentOutputConfig = try container.decodeIfPresent(
      DocumentOutputConfig.self, forKey: .documentOutputConfig)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .skipHumanReview) {
      self.skipHumanReview = value
    }
    self.processOptions = try container.decodeIfPresent(
      ProcessOptions.self, forKey: .processOptions)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.inputDocuments, forKey: .inputDocuments)
    try container.encodeIfPresent(self.documentOutputConfig, forKey: .documentOutputConfig)
    try container.encode(self.skipHumanReview, forKey: .skipHumanReview)
    try container.encodeIfPresent(self.processOptions, forKey: .processOptions)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.BatchProcessRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
