// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The common config to specify a set of documents used as input.
public struct BatchDocumentsInputConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The source. Make sure that the caller of the API has storage.objects.get
  /// access to the buckets.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `BatchDocumentsInputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchDocumentsInputConfig().with { $0.gcsPrefix = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsPrefix = "gcsPrefix"
    case gcsDocuments = "gcsDocuments"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsPrefix = try container.decodeIfPresent(GcsPrefix?.self, forKey: .gcsPrefix) {
      try sourceCheckAndSet(.gcsPrefix(gcsPrefix))
    }
    if let gcsDocuments = try container.decodeIfPresent(GcsDocuments?.self, forKey: .gcsDocuments) {
      try sourceCheckAndSet(.gcsDocuments(gcsDocuments))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.source {
      switch choice {
      case .gcsPrefix(let value):
        try container.encode(value, forKey: .gcsPrefix)
      case .gcsDocuments(let value):
        try container.encode(value, forKey: .gcsDocuments)
      }
    }
  }

  /// The source. Make sure that the caller of the API has storage.objects.get
  /// access to the buckets.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// The set of documents that match the specified Cloud Storage `gcs_prefix`.
    indirect case gcsPrefix(GcsPrefix?)
    /// The set of documents individually specified on Cloud Storage.
    indirect case gcsDocuments(GcsDocuments?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.BatchDocumentsInputConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
