// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The long-running operation metadata for
/// [BatchProcessDocuments][google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments].
///
/// [google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]: <doc:DocumentProcessorServiceClient/batchProcessDocuments(request:options:)>
public struct BatchProcessMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The state of the current batch processing.
  public var state: BatchProcessMetadata.State = BatchProcessMetadata.State()

  /// A message providing more details about the current state of processing.
  /// For example, the error message if the operation is failed.
  public var stateMessage: Swift.String = Swift.String()

  /// The creation time of the operation.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// The last update time of the operation.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// The list of response details of each document.
  public var individualProcessStatuses: [BatchProcessMetadata.IndividualProcessStatus] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchProcessMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchProcessMetadata().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let state = CodingKeys(stringValue: "state")
    static let stateMessage = CodingKeys(stringValue: "stateMessage")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let individualProcessStatuses = CodingKeys(stringValue: "individualProcessStatuses")

    static let _knownKeys: Set<Swift.String> = [
      "state",
      "stateMessage",
      "createTime",
      "updateTime",
      "individualProcessStatuses",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(BatchProcessMetadata.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateMessage) {
      self.stateMessage = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(
      [BatchProcessMetadata.IndividualProcessStatus].self, forKey: .individualProcessStatuses)
    {
      self.individualProcessStatuses = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateMessage, forKey: .stateMessage)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.individualProcessStatuses, forKey: .individualProcessStatuses)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The status of a each individual document in the batch process.
  public struct IndividualProcessStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The source of the document, same as the
    /// [input_gcs_source][google.cloud.documentai.v1.BatchProcessMetadata.IndividualProcessStatus.input_gcs_source]
    /// field in the request when the batch process started.
    ///
    /// [google.cloud.documentai.v1.BatchProcessMetadata.IndividualProcessStatus.input_gcs_source]: <doc:BatchProcessMetadata/IndividualProcessStatus/inputGcsSource>
    public var inputGcsSource: Swift.String = Swift.String()

    /// The status processing the document.
    public var status: GoogleRpc.Status? = nil

    /// The Cloud Storage output destination (in the request as
    /// [DocumentOutputConfig.GcsOutputConfig.gcs_uri][google.cloud.documentai.v1.DocumentOutputConfig.GcsOutputConfig.gcs_uri])
    /// of the processed document if it was successful, otherwise empty.
    ///
    /// [google.cloud.documentai.v1.DocumentOutputConfig.GcsOutputConfig.gcs_uri]: <doc:DocumentOutputConfig/GcsOutputConfig/gcsUri>
    public var outputGcsDestination: Swift.String = Swift.String()

    /// The status of human review on the processed document.
    public var humanReviewStatus: HumanReviewStatus? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IndividualProcessStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IndividualProcessStatus().with { $0.inputGcsSource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inputGcsSource = CodingKeys(stringValue: "inputGcsSource")
      static let status = CodingKeys(stringValue: "status")
      static let outputGcsDestination = CodingKeys(stringValue: "outputGcsDestination")
      static let humanReviewStatus = CodingKeys(stringValue: "humanReviewStatus")

      static let _knownKeys: Set<Swift.String> = [
        "inputGcsSource",
        "status",
        "outputGcsDestination",
        "humanReviewStatus",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputGcsSource) {
        self.inputGcsSource = value
      }
      self.status = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .status)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputGcsDestination)
      {
        self.outputGcsDestination = value
      }
      self.humanReviewStatus = try container.decodeIfPresent(
        HumanReviewStatus.self, forKey: .humanReviewStatus)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.inputGcsSource, forKey: .inputGcsSource)
      try container.encodeIfPresent(self.status, forKey: .status)
      try container.encode(self.outputGcsDestination, forKey: .outputGcsDestination)
      try container.encodeIfPresent(self.humanReviewStatus, forKey: .humanReviewStatus)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.documentai.v1.BatchProcessMetadata.IndividualProcessStatus"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Possible states of the batch processing operation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// The default value. This value is used if the state is omitted.
    case unspecified
    /// Request operation is waiting for scheduling.
    case waiting
    /// Request is being processed.
    case running
    /// The batch processing completed successfully.
    case succeeded
    /// The batch processing was being cancelled.
    case cancelling
    /// The batch processing was cancelled.
    case cancelled
    /// The batch processing has failed.
    case failed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .waiting: return 1
      case .running: return 2
      case .succeeded: return 3
      case .cancelling: return 4
      case .cancelled: return 5
      case .failed: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .waiting: return "WAITING"
      case .running: return "RUNNING"
      case .succeeded: return "SUCCEEDED"
      case .cancelling: return "CANCELLING"
      case .cancelled: return "CANCELLED"
      case .failed: return "FAILED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "WAITING": self = .waiting
      case "RUNNING": self = .running
      case "SUCCEEDED": self = .succeeded
      case "CANCELLING": self = .cancelling
      case "CANCELLED": self = .cancelled
      case "FAILED": self = .failed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .waiting
      case 2: self = .running
      case 3: self = .succeeded
      case 4: self = .cancelling
      case 5: self = .cancelled
      case 6: self = .failed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .waiting: return try container.encode("WAITING")
      case .running: return try container.encode("RUNNING")
      case .succeeded: return try container.encode("SUCCEEDED")
      case .cancelling: return try container.encode("CANCELLING")
      case .cancelled: return try container.encode("CANCELLED")
      case .failed: return try container.encode("FAILED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.BatchProcessMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
