// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for the
/// [CreateProcessor][google.cloud.documentai.v1.DocumentProcessorService.CreateProcessor]
/// method. Notice this request is sent to a regionalized backend service. If the
/// [ProcessorType][google.cloud.documentai.v1.ProcessorType] isn't available in
/// that region, the creation fails.
///
/// [google.cloud.documentai.v1.DocumentProcessorService.CreateProcessor]: <doc:DocumentProcessorServiceClient/createProcessor(request:options:)>
/// [google.cloud.documentai.v1.ProcessorType]: <doc:ProcessorType>
public struct CreateProcessorRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The parent (project and location) under which to create the
  /// processor. Format: `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. The processor to be created, requires
  /// [Processor.type][google.cloud.documentai.v1.Processor.type] and
  /// [Processor.display_name][google.cloud.documentai.v1.Processor.display_name]
  /// to be set. Also, the
  /// [Processor.kms_key_name][google.cloud.documentai.v1.Processor.kms_key_name]
  /// field must be set if the processor is under CMEK.
  ///
  /// [google.cloud.documentai.v1.Processor.display_name]: <doc:Processor/displayName>
  /// [google.cloud.documentai.v1.Processor.kms_key_name]: <doc:Processor/kmsKeyName>
  /// [google.cloud.documentai.v1.Processor.type]: <doc:Processor/type>
  public var processor: Processor? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateProcessorRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateProcessorRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let processor = CodingKeys(stringValue: "processor")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "processor",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    self.processor = try container.decodeIfPresent(Processor.self, forKey: .processor)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encodeIfPresent(self.processor, forKey: .processor)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.CreateProcessorRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
