// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the
/// [CreateProcessor][google.cloud.documentai.v1.DocumentProcessorService.CreateProcessor]
/// method. Notice this request is sent to a regionalized backend service. If the
/// [ProcessorType][google.cloud.documentai.v1.ProcessorType] isn't available in
/// that region, the creation fails.
///
/// [google.cloud.documentai.v1.DocumentProcessorService.CreateProcessor]: <doc:DocumentProcessorServiceClient/createProcessor(request:)>
/// [google.cloud.documentai.v1.ProcessorType]: <doc:ProcessorType>
public struct CreateProcessorRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent (project and location) under which to create the
  /// processor. Format: `projects/{project}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. The processor to be created, requires
  /// [Processor.type][google.cloud.documentai.v1.Processor.type] and
  /// [Processor.display_name][google.cloud.documentai.v1.Processor.display_name]
  /// to be set. Also, the
  /// [Processor.kms_key_name][google.cloud.documentai.v1.Processor.kms_key_name]
  /// field must be set if the processor is under CMEK.
  ///
  /// [google.cloud.documentai.v1.Processor.display_name]: <doc:Processor/displayName>
  /// [google.cloud.documentai.v1.Processor.kms_key_name]: <doc:Processor/kmsKeyName>
  /// [google.cloud.documentai.v1.Processor.type]: <doc:Processor/type>
  public var processor: Processor? = nil

  /// Initialize a new instance of `CreateProcessorRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateProcessorRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.CreateProcessorRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
