// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Config that controls the output of documents. All documents will be written
/// as a JSON file.
public struct DocumentOutputConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The destination of the results.
  public var destination: DestinationOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DocumentOutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DocumentOutputConfig().with { $0.gcsOutputConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let gcsOutputConfig = CodingKeys(stringValue: "gcsOutputConfig")

    static let _knownKeys: Set<Swift.String> = [
      "gcsOutputConfig"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var destination: DestinationOneOf? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsOutputConfig = try container.decodeIfPresent(
      DocumentOutputConfig.GcsOutputConfig?.self, forKey: .gcsOutputConfig)
    {
      try destinationCheckAndSet(.gcsOutputConfig(gcsOutputConfig))
    }
    self.destination = destination
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.destination {
      switch choice {
      case .gcsOutputConfig(let value):
        try container.encode(value, forKey: .gcsOutputConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The configuration used when outputting documents.
  public struct GcsOutputConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The Cloud Storage uri (a directory) of the output.
    public var gcsUri: Swift.String = Swift.String()

    /// Specifies which fields to include in the output documents.
    /// Only supports top level document and pages field so it must be in the
    /// form of `{document_field_name}` or `pages.{page_field_name}`.
    public var fieldMask: GoogleWKT.WKTFieldMask? = nil

    /// Specifies the sharding config for the output document.
    public var shardingConfig: DocumentOutputConfig.GcsOutputConfig.ShardingConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `GcsOutputConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GcsOutputConfig().with { $0.gcsUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let gcsUri = CodingKeys(stringValue: "gcsUri")
      static let fieldMask = CodingKeys(stringValue: "fieldMask")
      static let shardingConfig = CodingKeys(stringValue: "shardingConfig")

      static let _knownKeys: Set<Swift.String> = [
        "gcsUri",
        "fieldMask",
        "shardingConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gcsUri) {
        self.gcsUri = value
      }
      self.fieldMask = try container.decodeIfPresent(
        GoogleWKT.WKTFieldMask.self, forKey: .fieldMask)
      self.shardingConfig = try container.decodeIfPresent(
        DocumentOutputConfig.GcsOutputConfig.ShardingConfig.self, forKey: .shardingConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.gcsUri, forKey: .gcsUri)
      try container.encodeIfPresent(self.fieldMask, forKey: .fieldMask)
      try container.encodeIfPresent(self.shardingConfig, forKey: .shardingConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The sharding config for the output document.
    public struct ShardingConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The number of pages per shard.
      public var pagesPerShard: Swift.Int32 = Swift.Int32()

      /// The number of overlapping pages between consecutive shards.
      public var pagesOverlap: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ShardingConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ShardingConfig().with { $0.pagesPerShard = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let pagesPerShard = CodingKeys(stringValue: "pagesPerShard")
        static let pagesOverlap = CodingKeys(stringValue: "pagesOverlap")

        static let _knownKeys: Set<Swift.String> = [
          "pagesPerShard",
          "pagesOverlap",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pagesPerShard) {
          self.pagesPerShard = value
        }
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pagesOverlap) {
          self.pagesOverlap = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.pagesPerShard, forKey: .pagesPerShard)
        try container.encode(self.pagesOverlap, forKey: .pagesOverlap)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.documentai.v1.DocumentOutputConfig.GcsOutputConfig.ShardingConfig"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.DocumentOutputConfig.GcsOutputConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The destination of the results.
  public enum DestinationOneOf: Codable, Equatable, Sendable {
    /// Output config to write the results to Cloud Storage.
    indirect case gcsOutputConfig(DocumentOutputConfig.GcsOutputConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.DocumentOutputConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
