// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol DocumentProcessorServiceStub: Sendable {
    func processDocument(
      request: ProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ProcessResponse

    func batchProcessDocuments(
      request: BatchProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func fetchProcessorTypes(
      request: FetchProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse

    func listProcessorTypes(
      request: ListProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse

    func getProcessorType(
      request: GetProcessorTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ProcessorType

    func listProcessors(
      request: ListProcessorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListProcessorsResponse

    func getProcessor(
      request: GetProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.Processor

    func trainProcessorVersion(
      request: TrainProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getProcessorVersion(
      request: GetProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ProcessorVersion

    func listProcessorVersions(
      request: ListProcessorVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse

    func deleteProcessorVersion(
      request: DeleteProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deployProcessorVersion(
      request: DeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func undeployProcessorVersion(
      request: UndeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createProcessor(
      request: CreateProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.Processor

    func deleteProcessor(
      request: DeleteProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func enableProcessor(
      request: EnableProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func disableProcessor(
      request: DisableProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func setDefaultProcessorVersion(
      request: SetDefaultProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func reviewDocument(
      request: ReviewDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func evaluateProcessorVersion(
      request: EvaluateProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getEvaluation(
      request: GetEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.Evaluation

    func listEvaluations(
      request: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListEvaluationsResponse

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
