// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Service to call Document AI to process documents according to the
/// processor's definition. Processors are built using state-of-the-art Google
/// AI such as natural language, computer vision, and translation to extract
/// structured information from unstructured or semi-structured documents.
///
/// @Snippet(path: "DocumentProcessorServiceQuickstart")
public class DocumentProcessorServiceClient: Clients.DocumentProcessorServiceProtocol {
  let inner: any Clients.DocumentProcessorServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `DocumentProcessorServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DocumentProcessorServiceStub =
      try Clients.DocumentProcessorServiceTransport(options)
    inner = Clients.DocumentProcessorServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DocumentProcessorServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Processes a single document.
  ///
  /// @Snippet(path: "DocumentProcessorService_ProcessDocument")
  public func processDocument(
    request: ProcessRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ProcessResponse {
    try await self.inner.processDocument(request: request, options: options)
  }

  /// LRO endpoint to batch process many documents. The output is written
  /// to Cloud Storage as JSON in the [Document] format.
  ///
  /// @Snippet(path: "DocumentProcessorService_BatchProcessDocuments")
  public func batchProcessDocuments(
    request: BatchProcessRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.batchProcessDocuments(request: request, options: options)
  }

  /// LRO endpoint to batch process many documents. The output is written
  /// to Cloud Storage as JSON in the [Document] format.
  ///
  /// @Snippet(path: "DocumentProcessorService_BatchProcessDocuments")
  public func batchProcessDocuments(
    withPolling: BatchProcessRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchProcessResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<BatchProcessResponse>.State in
      return try op._extractStatus(BatchProcessResponse.self)
    }
    let rawOp = try await self.batchProcessDocuments(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchProcessResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Fetches processor types. Note that we don't use
  /// [ListProcessorTypes][google.cloud.documentai.v1.DocumentProcessorService.ListProcessorTypes]
  /// here, because it isn't paginated.
  ///
  /// [google.cloud.documentai.v1.DocumentProcessorService.ListProcessorTypes]: <doc:DocumentProcessorServiceClient/listProcessorTypes(request:options:)>
  ///
  /// @Snippet(path: "DocumentProcessorService_FetchProcessorTypes")
  public func fetchProcessorTypes(
    request: FetchProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse {
    try await self.inner.fetchProcessorTypes(request: request, options: options)
  }

  /// Lists the processor types that exist.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListProcessorTypes")
  public func listProcessorTypes(
    request: ListProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse {
    try await self.inner.listProcessorTypes(request: request, options: options)
  }

  /// Lists the processor types that exist.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListProcessorTypes")
  public func listProcessorTypes(
    byItem: ListProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ProcessorType, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProcessorTypes(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a processor type detail.
  ///
  /// @Snippet(path: "DocumentProcessorService_GetProcessorType")
  public func getProcessorType(
    request: GetProcessorTypeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ProcessorType {
    try await self.inner.getProcessorType(request: request, options: options)
  }

  /// Lists all processors which belong to this project.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListProcessors")
  public func listProcessors(
    request: ListProcessorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListProcessorsResponse {
    try await self.inner.listProcessors(request: request, options: options)
  }

  /// Lists all processors which belong to this project.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListProcessors")
  public func listProcessors(
    byItem: ListProcessorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Processor, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListProcessorsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProcessors(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a processor detail.
  ///
  /// @Snippet(path: "DocumentProcessorService_GetProcessor")
  public func getProcessor(
    request: GetProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.Processor {
    try await self.inner.getProcessor(request: request, options: options)
  }

  /// Trains a new processor version.
  /// Operation metadata is returned as
  /// [TrainProcessorVersionMetadata][google.cloud.documentai.v1.TrainProcessorVersionMetadata].
  ///
  /// [google.cloud.documentai.v1.TrainProcessorVersionMetadata]: <doc:TrainProcessorVersionMetadata>
  ///
  /// @Snippet(path: "DocumentProcessorService_TrainProcessorVersion")
  public func trainProcessorVersion(
    request: TrainProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.trainProcessorVersion(request: request, options: options)
  }

  /// Trains a new processor version.
  /// Operation metadata is returned as
  /// [TrainProcessorVersionMetadata][google.cloud.documentai.v1.TrainProcessorVersionMetadata].
  ///
  /// [google.cloud.documentai.v1.TrainProcessorVersionMetadata]: <doc:TrainProcessorVersionMetadata>
  ///
  /// @Snippet(path: "DocumentProcessorService_TrainProcessorVersion")
  public func trainProcessorVersion(
    withPolling: TrainProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TrainProcessorVersionResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<TrainProcessorVersionResponse>.State in
      return try op._extractStatus(TrainProcessorVersionResponse.self)
    }
    let rawOp = try await self.trainProcessorVersion(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<TrainProcessorVersionResponse>.State
      in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a processor version detail.
  ///
  /// @Snippet(path: "DocumentProcessorService_GetProcessorVersion")
  public func getProcessorVersion(
    request: GetProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ProcessorVersion {
    try await self.inner.getProcessorVersion(request: request, options: options)
  }

  /// Lists all versions of a processor.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListProcessorVersions")
  public func listProcessorVersions(
    request: ListProcessorVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse {
    try await self.inner.listProcessorVersions(request: request, options: options)
  }

  /// Lists all versions of a processor.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListProcessorVersions")
  public func listProcessorVersions(
    byItem: ListProcessorVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ProcessorVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listProcessorVersions(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deletes the processor version, all artifacts under the processor version
  /// will be deleted.
  ///
  /// @Snippet(path: "DocumentProcessorService_DeleteProcessorVersion")
  public func deleteProcessorVersion(
    request: DeleteProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteProcessorVersion(request: request, options: options)
  }

  /// Deletes the processor version, all artifacts under the processor version
  /// will be deleted.
  ///
  /// @Snippet(path: "DocumentProcessorService_DeleteProcessorVersion")
  public func deleteProcessorVersion(
    withPolling: DeleteProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteProcessorVersion(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deploys the processor version.
  ///
  /// @Snippet(path: "DocumentProcessorService_DeployProcessorVersion")
  public func deployProcessorVersion(
    request: DeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deployProcessorVersion(request: request, options: options)
  }

  /// Deploys the processor version.
  ///
  /// @Snippet(path: "DocumentProcessorService_DeployProcessorVersion")
  public func deployProcessorVersion(
    withPolling: DeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DeployProcessorVersionResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<DeployProcessorVersionResponse>.State in
      return try op._extractStatus(DeployProcessorVersionResponse.self)
    }
    let rawOp = try await self.deployProcessorVersion(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<DeployProcessorVersionResponse>.State
      in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Undeploys the processor version.
  ///
  /// @Snippet(path: "DocumentProcessorService_UndeployProcessorVersion")
  public func undeployProcessorVersion(
    request: UndeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.undeployProcessorVersion(request: request, options: options)
  }

  /// Undeploys the processor version.
  ///
  /// @Snippet(path: "DocumentProcessorService_UndeployProcessorVersion")
  public func undeployProcessorVersion(
    withPolling: UndeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<UndeployProcessorVersionResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<UndeployProcessorVersionResponse>.State in
      return try op._extractStatus(UndeployProcessorVersionResponse.self)
    }
    let rawOp = try await self.undeployProcessorVersion(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<UndeployProcessorVersionResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Creates a processor from the
  /// [ProcessorType][google.cloud.documentai.v1.ProcessorType] provided. The
  /// processor will be at `ENABLED` state by default after its creation. Note
  /// that this method requires the `documentai.processors.create` permission on
  /// the project, which is highly privileged. A user or service account with
  /// this permission can create new processors that can interact with any gcs
  /// bucket in your project.
  ///
  /// [google.cloud.documentai.v1.ProcessorType]: <doc:ProcessorType>
  ///
  /// @Snippet(path: "DocumentProcessorService_CreateProcessor")
  public func createProcessor(
    request: CreateProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.Processor {
    try await self.inner.createProcessor(request: request, options: options)
  }

  /// Deletes the processor, unloads all deployed model artifacts if it was
  /// enabled and then deletes all artifacts associated with this processor.
  ///
  /// @Snippet(path: "DocumentProcessorService_DeleteProcessor")
  public func deleteProcessor(
    request: DeleteProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteProcessor(request: request, options: options)
  }

  /// Deletes the processor, unloads all deployed model artifacts if it was
  /// enabled and then deletes all artifacts associated with this processor.
  ///
  /// @Snippet(path: "DocumentProcessorService_DeleteProcessor")
  public func deleteProcessor(
    withPolling: DeleteProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteProcessor(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Enables a processor
  ///
  /// @Snippet(path: "DocumentProcessorService_EnableProcessor")
  public func enableProcessor(
    request: EnableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.enableProcessor(request: request, options: options)
  }

  /// Enables a processor
  ///
  /// @Snippet(path: "DocumentProcessorService_EnableProcessor")
  public func enableProcessor(
    withPolling: EnableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<EnableProcessorResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<EnableProcessorResponse>.State in
      return try op._extractStatus(EnableProcessorResponse.self)
    }
    let rawOp = try await self.enableProcessor(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<EnableProcessorResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Disables a processor
  ///
  /// @Snippet(path: "DocumentProcessorService_DisableProcessor")
  public func disableProcessor(
    request: DisableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.disableProcessor(request: request, options: options)
  }

  /// Disables a processor
  ///
  /// @Snippet(path: "DocumentProcessorService_DisableProcessor")
  public func disableProcessor(
    withPolling: DisableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DisableProcessorResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<DisableProcessorResponse>.State in
      return try op._extractStatus(DisableProcessorResponse.self)
    }
    let rawOp = try await self.disableProcessor(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<DisableProcessorResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Set the default (active) version of a
  /// [Processor][google.cloud.documentai.v1.Processor] that will be used in
  /// [ProcessDocument][google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]
  /// and
  /// [BatchProcessDocuments][google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments].
  ///
  /// [google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]: <doc:DocumentProcessorServiceClient/batchProcessDocuments(request:options:)>
  /// [google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]: <doc:DocumentProcessorServiceClient/processDocument(request:options:)>
  /// [google.cloud.documentai.v1.Processor]: <doc:Processor>
  ///
  /// @Snippet(path: "DocumentProcessorService_SetDefaultProcessorVersion")
  public func setDefaultProcessorVersion(
    request: SetDefaultProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.setDefaultProcessorVersion(request: request, options: options)
  }

  /// Set the default (active) version of a
  /// [Processor][google.cloud.documentai.v1.Processor] that will be used in
  /// [ProcessDocument][google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]
  /// and
  /// [BatchProcessDocuments][google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments].
  ///
  /// [google.cloud.documentai.v1.DocumentProcessorService.BatchProcessDocuments]: <doc:DocumentProcessorServiceClient/batchProcessDocuments(request:options:)>
  /// [google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]: <doc:DocumentProcessorServiceClient/processDocument(request:options:)>
  /// [google.cloud.documentai.v1.Processor]: <doc:Processor>
  ///
  /// @Snippet(path: "DocumentProcessorService_SetDefaultProcessorVersion")
  public func setDefaultProcessorVersion(
    withPolling: SetDefaultProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<SetDefaultProcessorVersionResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<SetDefaultProcessorVersionResponse>.State in
      return try op._extractStatus(SetDefaultProcessorVersionResponse.self)
    }
    let rawOp = try await self.setDefaultProcessorVersion(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<SetDefaultProcessorVersionResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Send a document for Human Review. The input document should be processed by
  /// the specified processor.
  ///
  /// @Snippet(path: "DocumentProcessorService_ReviewDocument")
  public func reviewDocument(
    request: ReviewDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.reviewDocument(request: request, options: options)
  }

  /// Send a document for Human Review. The input document should be processed by
  /// the specified processor.
  ///
  /// @Snippet(path: "DocumentProcessorService_ReviewDocument")
  public func reviewDocument(
    withPolling: ReviewDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ReviewDocumentResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ReviewDocumentResponse>.State in
      return try op._extractStatus(ReviewDocumentResponse.self)
    }
    let rawOp = try await self.reviewDocument(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ReviewDocumentResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Evaluates a ProcessorVersion against annotated documents, producing an
  /// Evaluation.
  ///
  /// @Snippet(path: "DocumentProcessorService_EvaluateProcessorVersion")
  public func evaluateProcessorVersion(
    request: EvaluateProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.evaluateProcessorVersion(request: request, options: options)
  }

  /// Evaluates a ProcessorVersion against annotated documents, producing an
  /// Evaluation.
  ///
  /// @Snippet(path: "DocumentProcessorService_EvaluateProcessorVersion")
  public func evaluateProcessorVersion(
    withPolling: EvaluateProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<EvaluateProcessorVersionResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<EvaluateProcessorVersionResponse>.State in
      return try op._extractStatus(EvaluateProcessorVersionResponse.self)
    }
    let rawOp = try await self.evaluateProcessorVersion(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<EvaluateProcessorVersionResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Retrieves a specific evaluation.
  ///
  /// @Snippet(path: "DocumentProcessorService_GetEvaluation")
  public func getEvaluation(
    request: GetEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.Evaluation {
    try await self.inner.getEvaluation(request: request, options: options)
  }

  /// Retrieves a set of evaluations for a given processor version.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListEvaluations")
  public func listEvaluations(
    request: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListEvaluationsResponse {
    try await self.inner.listEvaluations(request: request, options: options)
  }

  /// Retrieves a set of evaluations for a given processor version.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListEvaluations")
  public func listEvaluations(
    byItem: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListEvaluationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listEvaluations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "DocumentProcessorService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "DocumentProcessorService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DocumentProcessorService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DocumentProcessorService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DocumentProcessorService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DocumentProcessorService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DocumentProcessorServiceClient`.
  ///
  /// To mock `DocumentProcessorServiceClient` change your functions to receive
  /// `some DocumentProcessorServiceProtocol` or `any DocumentProcessorServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DocumentProcessorServiceProtocol {
    /// See `DocumentProcessorServiceClient.processDocument`.
    func processDocument(request: ProcessRequest) async throws
      -> GoogleCloudDocumentAIV1.ProcessResponse

    /// See `DocumentProcessorServiceClient.processDocument`.
    func processDocument(
      name: Swift.String,
    ) async throws -> GoogleCloudDocumentAIV1.ProcessResponse

    /// See `DocumentProcessorServiceClient.batchProcessDocuments`.
    func batchProcessDocuments(request: BatchProcessRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.batchProcessDocuments`.
    func batchProcessDocuments(withPolling: BatchProcessRequest) async throws -> any GoogleCloudGax
      .PollableOperation<BatchProcessResponse>

    /// See `DocumentProcessorServiceClient.batchProcessDocuments`.
    func batchProcessDocuments(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchProcessResponse>

    /// See `DocumentProcessorServiceClient.fetchProcessorTypes`.
    func fetchProcessorTypes(request: FetchProcessorTypesRequest) async throws
      -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse

    /// See `DocumentProcessorServiceClient.fetchProcessorTypes`.
    func fetchProcessorTypes(
      parent: Swift.String,
    ) async throws -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse

    /// See `DocumentProcessorServiceClient.listProcessorTypes`.
    func listProcessorTypes(request: ListProcessorTypesRequest) async throws
      -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse

    /// See `DocumentProcessorServiceClient.listProcessorTypes`.
    func listProcessorTypes(
      byItem: ListProcessorTypesRequest
    ) throws -> any AsyncSequence<ProcessorType, Swift.Error>

    /// See `DocumentProcessorServiceClient.listProcessorTypes`.
    func listProcessorTypes(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ProcessorType, Swift.Error>

    /// See `DocumentProcessorServiceClient.getProcessorType`.
    func getProcessorType(request: GetProcessorTypeRequest) async throws
      -> GoogleCloudDocumentAIV1.ProcessorType

    /// See `DocumentProcessorServiceClient.getProcessorType`.
    func getProcessorType(
      name: Swift.String,
    ) async throws -> GoogleCloudDocumentAIV1.ProcessorType

    /// See `DocumentProcessorServiceClient.listProcessors`.
    func listProcessors(request: ListProcessorsRequest) async throws
      -> GoogleCloudDocumentAIV1.ListProcessorsResponse

    /// See `DocumentProcessorServiceClient.listProcessors`.
    func listProcessors(
      byItem: ListProcessorsRequest
    ) throws -> any AsyncSequence<Processor, Swift.Error>

    /// See `DocumentProcessorServiceClient.listProcessors`.
    func listProcessors(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Processor, Swift.Error>

    /// See `DocumentProcessorServiceClient.getProcessor`.
    func getProcessor(request: GetProcessorRequest) async throws
      -> GoogleCloudDocumentAIV1.Processor

    /// See `DocumentProcessorServiceClient.getProcessor`.
    func getProcessor(
      name: Swift.String,
    ) async throws -> GoogleCloudDocumentAIV1.Processor

    /// See `DocumentProcessorServiceClient.trainProcessorVersion`.
    func trainProcessorVersion(request: TrainProcessorVersionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.trainProcessorVersion`.
    func trainProcessorVersion(withPolling: TrainProcessorVersionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<TrainProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.trainProcessorVersion`.
    func trainProcessorVersion(
      parent: Swift.String,
      processorVersion: ProcessorVersion?,
    ) async throws -> any GoogleCloudGax.PollableOperation<TrainProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.getProcessorVersion`.
    func getProcessorVersion(request: GetProcessorVersionRequest) async throws
      -> GoogleCloudDocumentAIV1.ProcessorVersion

    /// See `DocumentProcessorServiceClient.getProcessorVersion`.
    func getProcessorVersion(
      name: Swift.String,
    ) async throws -> GoogleCloudDocumentAIV1.ProcessorVersion

    /// See `DocumentProcessorServiceClient.listProcessorVersions`.
    func listProcessorVersions(request: ListProcessorVersionsRequest) async throws
      -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse

    /// See `DocumentProcessorServiceClient.listProcessorVersions`.
    func listProcessorVersions(
      byItem: ListProcessorVersionsRequest
    ) throws -> any AsyncSequence<ProcessorVersion, Swift.Error>

    /// See `DocumentProcessorServiceClient.listProcessorVersions`.
    func listProcessorVersions(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ProcessorVersion, Swift.Error>

    /// See `DocumentProcessorServiceClient.deleteProcessorVersion`.
    func deleteProcessorVersion(request: DeleteProcessorVersionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.deleteProcessorVersion`.
    func deleteProcessorVersion(withPolling: DeleteProcessorVersionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DocumentProcessorServiceClient.deleteProcessorVersion`.
    func deleteProcessorVersion(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DocumentProcessorServiceClient.deployProcessorVersion`.
    func deployProcessorVersion(request: DeployProcessorVersionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.deployProcessorVersion`.
    func deployProcessorVersion(withPolling: DeployProcessorVersionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<DeployProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.deployProcessorVersion`.
    func deployProcessorVersion(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<DeployProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.undeployProcessorVersion`.
    func undeployProcessorVersion(request: UndeployProcessorVersionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.undeployProcessorVersion`.
    func undeployProcessorVersion(withPolling: UndeployProcessorVersionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<UndeployProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.undeployProcessorVersion`.
    func undeployProcessorVersion(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<UndeployProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.createProcessor`.
    func createProcessor(request: CreateProcessorRequest) async throws
      -> GoogleCloudDocumentAIV1.Processor

    /// See `DocumentProcessorServiceClient.createProcessor`.
    func createProcessor(
      parent: Swift.String,
      processor: Processor?,
    ) async throws -> GoogleCloudDocumentAIV1.Processor

    /// See `DocumentProcessorServiceClient.deleteProcessor`.
    func deleteProcessor(request: DeleteProcessorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.deleteProcessor`.
    func deleteProcessor(withPolling: DeleteProcessorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `DocumentProcessorServiceClient.deleteProcessor`.
    func deleteProcessor(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DocumentProcessorServiceClient.enableProcessor`.
    func enableProcessor(request: EnableProcessorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.enableProcessor`.
    func enableProcessor(withPolling: EnableProcessorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<EnableProcessorResponse>

    /// See `DocumentProcessorServiceClient.disableProcessor`.
    func disableProcessor(request: DisableProcessorRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.disableProcessor`.
    func disableProcessor(withPolling: DisableProcessorRequest) async throws -> any GoogleCloudGax
      .PollableOperation<DisableProcessorResponse>

    /// See `DocumentProcessorServiceClient.setDefaultProcessorVersion`.
    func setDefaultProcessorVersion(request: SetDefaultProcessorVersionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.setDefaultProcessorVersion`.
    func setDefaultProcessorVersion(withPolling: SetDefaultProcessorVersionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<SetDefaultProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.reviewDocument`.
    func reviewDocument(request: ReviewDocumentRequest) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.reviewDocument`.
    func reviewDocument(withPolling: ReviewDocumentRequest) async throws -> any GoogleCloudGax
      .PollableOperation<ReviewDocumentResponse>

    /// See `DocumentProcessorServiceClient.reviewDocument`.
    func reviewDocument(
      humanReviewConfig: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<ReviewDocumentResponse>

    /// See `DocumentProcessorServiceClient.evaluateProcessorVersion`.
    func evaluateProcessorVersion(request: EvaluateProcessorVersionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.evaluateProcessorVersion`.
    func evaluateProcessorVersion(withPolling: EvaluateProcessorVersionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<EvaluateProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.evaluateProcessorVersion`.
    func evaluateProcessorVersion(
      processorVersion: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<EvaluateProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.getEvaluation`.
    func getEvaluation(request: GetEvaluationRequest) async throws
      -> GoogleCloudDocumentAIV1.Evaluation

    /// See `DocumentProcessorServiceClient.getEvaluation`.
    func getEvaluation(
      name: Swift.String,
    ) async throws -> GoogleCloudDocumentAIV1.Evaluation

    /// See `DocumentProcessorServiceClient.listEvaluations`.
    func listEvaluations(request: ListEvaluationsRequest) async throws
      -> GoogleCloudDocumentAIV1.ListEvaluationsResponse

    /// See `DocumentProcessorServiceClient.listEvaluations`.
    func listEvaluations(
      byItem: ListEvaluationsRequest
    ) throws -> any AsyncSequence<Evaluation, Swift.Error>

    /// See `DocumentProcessorServiceClient.listEvaluations`.
    func listEvaluations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Evaluation, Swift.Error>

    /// See `DocumentProcessorServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `DocumentProcessorServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DocumentProcessorServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `DocumentProcessorServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `DocumentProcessorServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DocumentProcessorServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DocumentProcessorServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `DocumentProcessorServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `DocumentProcessorServiceClient.processDocument`.
    func processDocument(
      request: ProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ProcessResponse

    /// See `DocumentProcessorServiceClient.batchProcessDocuments`.
    func batchProcessDocuments(
      request: BatchProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.batchProcessDocuments`.
    func batchProcessDocuments(
      withPolling: BatchProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<BatchProcessResponse>

    /// See `DocumentProcessorServiceClient.fetchProcessorTypes`.
    func fetchProcessorTypes(
      request: FetchProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse

    /// See `DocumentProcessorServiceClient.listProcessorTypes`.
    func listProcessorTypes(
      request: ListProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse

    /// See `DocumentProcessorServiceClient.listProcessorTypes`.
    func listProcessorTypes(
      byItem: ListProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ProcessorType, Swift.Error>

    /// See `DocumentProcessorServiceClient.getProcessorType`.
    func getProcessorType(
      request: GetProcessorTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ProcessorType

    /// See `DocumentProcessorServiceClient.listProcessors`.
    func listProcessors(
      request: ListProcessorsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListProcessorsResponse

    /// See `DocumentProcessorServiceClient.listProcessors`.
    func listProcessors(
      byItem: ListProcessorsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Processor, Swift.Error>

    /// See `DocumentProcessorServiceClient.getProcessor`.
    func getProcessor(
      request: GetProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.Processor

    /// See `DocumentProcessorServiceClient.trainProcessorVersion`.
    func trainProcessorVersion(
      request: TrainProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.trainProcessorVersion`.
    func trainProcessorVersion(
      withPolling: TrainProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<TrainProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.getProcessorVersion`.
    func getProcessorVersion(
      request: GetProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ProcessorVersion

    /// See `DocumentProcessorServiceClient.listProcessorVersions`.
    func listProcessorVersions(
      request: ListProcessorVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse

    /// See `DocumentProcessorServiceClient.listProcessorVersions`.
    func listProcessorVersions(
      byItem: ListProcessorVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ProcessorVersion, Swift.Error>

    /// See `DocumentProcessorServiceClient.deleteProcessorVersion`.
    func deleteProcessorVersion(
      request: DeleteProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.deleteProcessorVersion`.
    func deleteProcessorVersion(
      withPolling: DeleteProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DocumentProcessorServiceClient.deployProcessorVersion`.
    func deployProcessorVersion(
      request: DeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.deployProcessorVersion`.
    func deployProcessorVersion(
      withPolling: DeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DeployProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.undeployProcessorVersion`.
    func undeployProcessorVersion(
      request: UndeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.undeployProcessorVersion`.
    func undeployProcessorVersion(
      withPolling: UndeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<UndeployProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.createProcessor`.
    func createProcessor(
      request: CreateProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.Processor

    /// See `DocumentProcessorServiceClient.deleteProcessor`.
    func deleteProcessor(
      request: DeleteProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.deleteProcessor`.
    func deleteProcessor(
      withPolling: DeleteProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DocumentProcessorServiceClient.enableProcessor`.
    func enableProcessor(
      request: EnableProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.enableProcessor`.
    func enableProcessor(
      withPolling: EnableProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<EnableProcessorResponse>

    /// See `DocumentProcessorServiceClient.disableProcessor`.
    func disableProcessor(
      request: DisableProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.disableProcessor`.
    func disableProcessor(
      withPolling: DisableProcessorRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DisableProcessorResponse>

    /// See `DocumentProcessorServiceClient.setDefaultProcessorVersion`.
    func setDefaultProcessorVersion(
      request: SetDefaultProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.setDefaultProcessorVersion`.
    func setDefaultProcessorVersion(
      withPolling: SetDefaultProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<SetDefaultProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.reviewDocument`.
    func reviewDocument(
      request: ReviewDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.reviewDocument`.
    func reviewDocument(
      withPolling: ReviewDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ReviewDocumentResponse>

    /// See `DocumentProcessorServiceClient.evaluateProcessorVersion`.
    func evaluateProcessorVersion(
      request: EvaluateProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DocumentProcessorServiceClient.evaluateProcessorVersion`.
    func evaluateProcessorVersion(
      withPolling: EvaluateProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<EvaluateProcessorVersionResponse>

    /// See `DocumentProcessorServiceClient.getEvaluation`.
    func getEvaluation(
      request: GetEvaluationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.Evaluation

    /// See `DocumentProcessorServiceClient.listEvaluations`.
    func listEvaluations(
      request: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDocumentAIV1.ListEvaluationsResponse

    /// See `DocumentProcessorServiceClient.listEvaluations`.
    func listEvaluations(
      byItem: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Evaluation, Swift.Error>

    /// See `DocumentProcessorServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DocumentProcessorServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DocumentProcessorServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `DocumentProcessorServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DocumentProcessorServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DocumentProcessorServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DocumentProcessorServiceProtocol {
  public func processDocument(request: ProcessRequest) async throws
    -> GoogleCloudDocumentAIV1.ProcessResponse
  {
    try await self.processDocument(request: request, options: .init())
  }

  public func processDocument(
    request: ProcessRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ProcessResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func processDocument(
    name: Swift.String,
  ) async throws -> GoogleCloudDocumentAIV1.ProcessResponse {
    let request = ProcessRequest().with {
      $0.name = name
    }
    return try await self.processDocument(request: request)
  }

  public func batchProcessDocuments(request: BatchProcessRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.batchProcessDocuments(request: request, options: .init())
  }

  public func batchProcessDocuments(
    request: BatchProcessRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchProcessDocuments(withPolling: BatchProcessRequest) async throws
    -> any GoogleCloudGax.PollableOperation<BatchProcessResponse>
  {
    try await self.batchProcessDocuments(withPolling: withPolling, options: .init())
  }

  public func batchProcessDocuments(
    withPolling: BatchProcessRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchProcessResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<BatchProcessResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func batchProcessDocuments(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<BatchProcessResponse> {
    let request = BatchProcessRequest().with {
      $0.name = name
    }
    return try await self.batchProcessDocuments(withPolling: request)
  }

  public func fetchProcessorTypes(request: FetchProcessorTypesRequest) async throws
    -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse
  {
    try await self.fetchProcessorTypes(request: request, options: .init())
  }

  public func fetchProcessorTypes(
    request: FetchProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func fetchProcessorTypes(
    parent: Swift.String,
  ) async throws -> GoogleCloudDocumentAIV1.FetchProcessorTypesResponse {
    let request = FetchProcessorTypesRequest().with {
      $0.parent = parent
    }
    return try await self.fetchProcessorTypes(request: request)
  }

  public func listProcessorTypes(request: ListProcessorTypesRequest) async throws
    -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse
  {
    try await self.listProcessorTypes(request: request, options: .init())
  }

  public func listProcessorTypes(
    request: ListProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listProcessorTypes(
    byItem: ListProcessorTypesRequest
  ) throws -> any AsyncSequence<ProcessorType, Swift.Error> {
    try self.listProcessorTypes(byItem: byItem, options: .init())
  }

  public func listProcessorTypes(
    byItem: ListProcessorTypesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ProcessorType, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListProcessorTypesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProcessorTypes(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ProcessorType, Swift.Error> {
    let request = ListProcessorTypesRequest().with {
      $0.parent = parent
    }
    return try self.listProcessorTypes(byItem: request)
  }

  public func getProcessorType(request: GetProcessorTypeRequest) async throws
    -> GoogleCloudDocumentAIV1.ProcessorType
  {
    try await self.getProcessorType(request: request, options: .init())
  }

  public func getProcessorType(
    request: GetProcessorTypeRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ProcessorType {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getProcessorType(
    name: Swift.String,
  ) async throws -> GoogleCloudDocumentAIV1.ProcessorType {
    let request = GetProcessorTypeRequest().with {
      $0.name = name
    }
    return try await self.getProcessorType(request: request)
  }

  public func listProcessors(request: ListProcessorsRequest) async throws
    -> GoogleCloudDocumentAIV1.ListProcessorsResponse
  {
    try await self.listProcessors(request: request, options: .init())
  }

  public func listProcessors(
    request: ListProcessorsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListProcessorsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listProcessors(
    byItem: ListProcessorsRequest
  ) throws -> any AsyncSequence<Processor, Swift.Error> {
    try self.listProcessors(byItem: byItem, options: .init())
  }

  public func listProcessors(
    byItem: ListProcessorsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Processor, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListProcessorsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProcessors(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Processor, Swift.Error> {
    let request = ListProcessorsRequest().with {
      $0.parent = parent
    }
    return try self.listProcessors(byItem: request)
  }

  public func getProcessor(request: GetProcessorRequest) async throws
    -> GoogleCloudDocumentAIV1.Processor
  {
    try await self.getProcessor(request: request, options: .init())
  }

  public func getProcessor(
    request: GetProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.Processor {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getProcessor(
    name: Swift.String,
  ) async throws -> GoogleCloudDocumentAIV1.Processor {
    let request = GetProcessorRequest().with {
      $0.name = name
    }
    return try await self.getProcessor(request: request)
  }

  public func trainProcessorVersion(request: TrainProcessorVersionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.trainProcessorVersion(request: request, options: .init())
  }

  public func trainProcessorVersion(
    request: TrainProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func trainProcessorVersion(withPolling: TrainProcessorVersionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<TrainProcessorVersionResponse>
  {
    try await self.trainProcessorVersion(withPolling: withPolling, options: .init())
  }

  public func trainProcessorVersion(
    withPolling: TrainProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<TrainProcessorVersionResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<TrainProcessorVersionResponse>.State
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func trainProcessorVersion(
    parent: Swift.String,
    processorVersion: ProcessorVersion?,
  ) async throws -> any GoogleCloudGax.PollableOperation<TrainProcessorVersionResponse> {
    let request = TrainProcessorVersionRequest().with {
      $0.parent = parent
      $0.processorVersion = processorVersion
    }
    return try await self.trainProcessorVersion(withPolling: request)
  }

  public func getProcessorVersion(request: GetProcessorVersionRequest) async throws
    -> GoogleCloudDocumentAIV1.ProcessorVersion
  {
    try await self.getProcessorVersion(request: request, options: .init())
  }

  public func getProcessorVersion(
    request: GetProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ProcessorVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getProcessorVersion(
    name: Swift.String,
  ) async throws -> GoogleCloudDocumentAIV1.ProcessorVersion {
    let request = GetProcessorVersionRequest().with {
      $0.name = name
    }
    return try await self.getProcessorVersion(request: request)
  }

  public func listProcessorVersions(request: ListProcessorVersionsRequest) async throws
    -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse
  {
    try await self.listProcessorVersions(request: request, options: .init())
  }

  public func listProcessorVersions(
    request: ListProcessorVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listProcessorVersions(
    byItem: ListProcessorVersionsRequest
  ) throws -> any AsyncSequence<ProcessorVersion, Swift.Error> {
    try self.listProcessorVersions(byItem: byItem, options: .init())
  }

  public func listProcessorVersions(
    byItem: ListProcessorVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ProcessorVersion, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListProcessorVersionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listProcessorVersions(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ProcessorVersion, Swift.Error> {
    let request = ListProcessorVersionsRequest().with {
      $0.parent = parent
    }
    return try self.listProcessorVersions(byItem: request)
  }

  public func deleteProcessorVersion(request: DeleteProcessorVersionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteProcessorVersion(request: request, options: .init())
  }

  public func deleteProcessorVersion(
    request: DeleteProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteProcessorVersion(withPolling: DeleteProcessorVersionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteProcessorVersion(withPolling: withPolling, options: .init())
  }

  public func deleteProcessorVersion(
    withPolling: DeleteProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteProcessorVersion(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteProcessorVersionRequest().with {
      $0.name = name
    }
    return try await self.deleteProcessorVersion(withPolling: request)
  }

  public func deployProcessorVersion(request: DeployProcessorVersionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deployProcessorVersion(request: request, options: .init())
  }

  public func deployProcessorVersion(
    request: DeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deployProcessorVersion(withPolling: DeployProcessorVersionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DeployProcessorVersionResponse>
  {
    try await self.deployProcessorVersion(withPolling: withPolling, options: .init())
  }

  public func deployProcessorVersion(
    withPolling: DeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DeployProcessorVersionResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<DeployProcessorVersionResponse>.State
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deployProcessorVersion(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<DeployProcessorVersionResponse> {
    let request = DeployProcessorVersionRequest().with {
      $0.name = name
    }
    return try await self.deployProcessorVersion(withPolling: request)
  }

  public func undeployProcessorVersion(request: UndeployProcessorVersionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.undeployProcessorVersion(request: request, options: .init())
  }

  public func undeployProcessorVersion(
    request: UndeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func undeployProcessorVersion(withPolling: UndeployProcessorVersionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<UndeployProcessorVersionResponse>
  {
    try await self.undeployProcessorVersion(withPolling: withPolling, options: .init())
  }

  public func undeployProcessorVersion(
    withPolling: UndeployProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<UndeployProcessorVersionResponse> {
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<UndeployProcessorVersionResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func undeployProcessorVersion(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<UndeployProcessorVersionResponse> {
    let request = UndeployProcessorVersionRequest().with {
      $0.name = name
    }
    return try await self.undeployProcessorVersion(withPolling: request)
  }

  public func createProcessor(request: CreateProcessorRequest) async throws
    -> GoogleCloudDocumentAIV1.Processor
  {
    try await self.createProcessor(request: request, options: .init())
  }

  public func createProcessor(
    request: CreateProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.Processor {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createProcessor(
    parent: Swift.String,
    processor: Processor?,
  ) async throws -> GoogleCloudDocumentAIV1.Processor {
    let request = CreateProcessorRequest().with {
      $0.parent = parent
      $0.processor = processor
    }
    return try await self.createProcessor(request: request)
  }

  public func deleteProcessor(request: DeleteProcessorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteProcessor(request: request, options: .init())
  }

  public func deleteProcessor(
    request: DeleteProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteProcessor(withPolling: DeleteProcessorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteProcessor(withPolling: withPolling, options: .init())
  }

  public func deleteProcessor(
    withPolling: DeleteProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteProcessor(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteProcessorRequest().with {
      $0.name = name
    }
    return try await self.deleteProcessor(withPolling: request)
  }

  public func enableProcessor(request: EnableProcessorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.enableProcessor(request: request, options: .init())
  }

  public func enableProcessor(
    request: EnableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func enableProcessor(withPolling: EnableProcessorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<EnableProcessorResponse>
  {
    try await self.enableProcessor(withPolling: withPolling, options: .init())
  }

  public func enableProcessor(
    withPolling: EnableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<EnableProcessorResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<EnableProcessorResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func disableProcessor(request: DisableProcessorRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.disableProcessor(request: request, options: .init())
  }

  public func disableProcessor(
    request: DisableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func disableProcessor(withPolling: DisableProcessorRequest) async throws
    -> any GoogleCloudGax.PollableOperation<DisableProcessorResponse>
  {
    try await self.disableProcessor(withPolling: withPolling, options: .init())
  }

  public func disableProcessor(
    withPolling: DisableProcessorRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<DisableProcessorResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<DisableProcessorResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func setDefaultProcessorVersion(request: SetDefaultProcessorVersionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.setDefaultProcessorVersion(request: request, options: .init())
  }

  public func setDefaultProcessorVersion(
    request: SetDefaultProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setDefaultProcessorVersion(withPolling: SetDefaultProcessorVersionRequest)
    async throws -> any GoogleCloudGax.PollableOperation<SetDefaultProcessorVersionResponse>
  {
    try await self.setDefaultProcessorVersion(withPolling: withPolling, options: .init())
  }

  public func setDefaultProcessorVersion(
    withPolling: SetDefaultProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<SetDefaultProcessorVersionResponse> {
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<SetDefaultProcessorVersionResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func reviewDocument(request: ReviewDocumentRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.reviewDocument(request: request, options: .init())
  }

  public func reviewDocument(
    request: ReviewDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func reviewDocument(withPolling: ReviewDocumentRequest) async throws -> any GoogleCloudGax
    .PollableOperation<ReviewDocumentResponse>
  {
    try await self.reviewDocument(withPolling: withPolling, options: .init())
  }

  public func reviewDocument(
    withPolling: ReviewDocumentRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ReviewDocumentResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ReviewDocumentResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func reviewDocument(
    humanReviewConfig: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<ReviewDocumentResponse> {
    let request = ReviewDocumentRequest().with {
      $0.humanReviewConfig = humanReviewConfig
    }
    return try await self.reviewDocument(withPolling: request)
  }

  public func evaluateProcessorVersion(request: EvaluateProcessorVersionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.evaluateProcessorVersion(request: request, options: .init())
  }

  public func evaluateProcessorVersion(
    request: EvaluateProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func evaluateProcessorVersion(withPolling: EvaluateProcessorVersionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<EvaluateProcessorVersionResponse>
  {
    try await self.evaluateProcessorVersion(withPolling: withPolling, options: .init())
  }

  public func evaluateProcessorVersion(
    withPolling: EvaluateProcessorVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<EvaluateProcessorVersionResponse> {
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<EvaluateProcessorVersionResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func evaluateProcessorVersion(
    processorVersion: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<EvaluateProcessorVersionResponse> {
    let request = EvaluateProcessorVersionRequest().with {
      $0.processorVersion = processorVersion
    }
    return try await self.evaluateProcessorVersion(withPolling: request)
  }

  public func getEvaluation(request: GetEvaluationRequest) async throws
    -> GoogleCloudDocumentAIV1.Evaluation
  {
    try await self.getEvaluation(request: request, options: .init())
  }

  public func getEvaluation(
    request: GetEvaluationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.Evaluation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getEvaluation(
    name: Swift.String,
  ) async throws -> GoogleCloudDocumentAIV1.Evaluation {
    let request = GetEvaluationRequest().with {
      $0.name = name
    }
    return try await self.getEvaluation(request: request)
  }

  public func listEvaluations(request: ListEvaluationsRequest) async throws
    -> GoogleCloudDocumentAIV1.ListEvaluationsResponse
  {
    try await self.listEvaluations(request: request, options: .init())
  }

  public func listEvaluations(
    request: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDocumentAIV1.ListEvaluationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listEvaluations(
    byItem: ListEvaluationsRequest
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    try self.listEvaluations(byItem: byItem, options: .init())
  }

  public func listEvaluations(
    byItem: ListEvaluationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDocumentAIV1.ListEvaluationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listEvaluations(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Evaluation, Swift.Error> {
    let request = ListEvaluationsRequest().with {
      $0.parent = parent
    }
    return try self.listEvaluations(byItem: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
