// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Evaluates the given
/// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion] against the
/// supplied documents.
///
/// [google.cloud.documentai.v1.ProcessorVersion]: <doc:ProcessorVersion>
public struct EvaluateProcessorVersionRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion] to
  /// evaluate.
  /// `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`
  ///
  /// [google.cloud.documentai.v1.ProcessorVersion]: <doc:ProcessorVersion>
  public var processorVersion: Swift.String = Swift.String()

  /// Optional. The documents used in the evaluation. If unspecified, use the
  /// processor's dataset as evaluation input.
  public var evaluationDocuments: BatchDocumentsInputConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EvaluateProcessorVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EvaluateProcessorVersionRequest().with { $0.processorVersion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let processorVersion = CodingKeys(stringValue: "processorVersion")
    static let evaluationDocuments = CodingKeys(stringValue: "evaluationDocuments")

    static let _knownKeys: Set<Swift.String> = [
      "processorVersion",
      "evaluationDocuments",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .processorVersion) {
      self.processorVersion = value
    }
    self.evaluationDocuments = try container.decodeIfPresent(
      BatchDocumentsInputConfig.self, forKey: .evaluationDocuments)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.processorVersion, forKey: .processorVersion)
    try container.encodeIfPresent(self.evaluationDocuments, forKey: .evaluationDocuments)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.EvaluateProcessorVersionRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
