// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The status of human review on a processed document.
public struct HumanReviewStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The state of human review on the processing request.
  public var state: HumanReviewStatus.State = HumanReviewStatus.State()

  /// A message providing more details about the human review state.
  public var stateMessage: Swift.String = Swift.String()

  /// The name of the operation triggered by the processed document. This field
  /// is populated only when the
  /// [state][google.cloud.documentai.v1.HumanReviewStatus.state] is
  /// `HUMAN_REVIEW_IN_PROGRESS`. It has the same response type and metadata as
  /// the long-running operation returned by
  /// [ReviewDocument][google.cloud.documentai.v1.DocumentProcessorService.ReviewDocument].
  ///
  /// [google.cloud.documentai.v1.DocumentProcessorService.ReviewDocument]: <doc:DocumentProcessorServiceClient/reviewDocument(request:)>
  /// [google.cloud.documentai.v1.HumanReviewStatus.state]: <doc:HumanReviewStatus/state>
  public var humanReviewOperation: Swift.String = Swift.String()

  /// Initialize a new instance of `HumanReviewStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HumanReviewStatus().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The final state of human review on a processed document.
  public enum State: Codable, Equatable, Sendable {
    /// Human review state is unspecified. Most likely due to an internal error.
    case unspecified
    /// Human review is skipped for the document. This can happen because human
    /// review isn't enabled on the processor or the processing request has
    /// been set to skip this document.
    case skipped
    /// Human review validation is triggered and passed, so no review is needed.
    case validationPassed
    /// Human review validation is triggered and the document is under review.
    case inProgress
    /// Some error happened during triggering human review, see the
    /// [state_message][google.cloud.documentai.v1.HumanReviewStatus.state_message]
    /// for details.
    ///
    /// [google.cloud.documentai.v1.HumanReviewStatus.state_message]: <doc:HumanReviewStatus/stateMessage>
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .skipped: return 1
      case .validationPassed: return 2
      case .inProgress: return 3
      case .error: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .skipped: return "SKIPPED"
      case .validationPassed: return "VALIDATION_PASSED"
      case .inProgress: return "IN_PROGRESS"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "SKIPPED": self = .skipped
      case "VALIDATION_PASSED": self = .validationPassed
      case "IN_PROGRESS": self = .inProgress
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .skipped
      case 2: self = .validationPassed
      case 3: self = .inProgress
      case 4: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .skipped: return try container.encode(1)
      case .validationPassed: return try container.encode(2)
      case .inProgress: return try container.encode(3)
      case .error: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.HumanReviewStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
