// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Config for Document OCR.
public struct OcrConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Hints for the OCR model.
  public var hints: OcrConfig.Hints? = nil

  /// Enables special handling for PDFs with existing text information. Results
  /// in better text extraction quality in such PDF inputs.
  public var enableNativePdfParsing: Swift.Bool = Swift.Bool()

  /// Enables intelligent document quality scores after OCR. Can help with
  /// diagnosing why OCR responses are of poor quality for a given input.
  /// Adds additional latency comparable to regular OCR to the process call.
  public var enableImageQualityScores: Swift.Bool = Swift.Bool()

  /// A list of advanced OCR options to further fine-tune OCR behavior. Current
  /// valid values are:
  ///
  /// - `legacy_layout`: a heuristics layout detection algorithm, which serves as
  /// an alternative to the current ML-based layout detection algorithm.
  /// Customers can choose the best suitable layout algorithm based on their
  /// situation.
  public var advancedOcrOptions: [Swift.String] = []

  /// Includes symbol level OCR information if set to true.
  public var enableSymbol: Swift.Bool = Swift.Bool()

  /// Turn on font identification model and return font style information.
  /// Deprecated, use
  /// [PremiumFeatures.compute_style_info][google.cloud.documentai.v1.OcrConfig.PremiumFeatures.compute_style_info]
  /// instead.
  ///
  /// [google.cloud.documentai.v1.OcrConfig.PremiumFeatures.compute_style_info]: <doc:OcrConfig/PremiumFeatures/computeStyleInfo>
  @available(*, deprecated)
  public var computeStyleInfo: Swift.Bool = Swift.Bool()

  /// Turn off character box detector in OCR engine. Character box detection is
  /// enabled by default in OCR 2.0 (and later) processors.
  public var disableCharacterBoxesDetection: Swift.Bool = Swift.Bool()

  /// Configurations for premium OCR features.
  public var premiumFeatures: OcrConfig.PremiumFeatures? = nil

  /// Initialize a new instance of `OcrConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OcrConfig().with { $0.hints = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Hints for OCR Engine
  public struct Hints: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// List of BCP-47 language codes to use for OCR. In most cases, not
    /// specifying it yields the best results since it enables automatic language
    /// detection. For languages based on the Latin alphabet, setting hints is
    /// not needed. In rare cases, when the language of the text in the
    /// image is known, setting a hint will help get better results (although it
    /// will be a significant hindrance if the hint is wrong).
    public var languageHints: [Swift.String] = []

    /// Initialize a new instance of `Hints`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Hints().with { $0.languageHints = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.OcrConfig.Hints"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configurations for premium OCR features.
  public struct PremiumFeatures: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Turn on selection mark detector in OCR engine. Only available in OCR 2.0
    /// (and later) processors.
    public var enableSelectionMarkDetection: Swift.Bool = Swift.Bool()

    /// Turn on font identification model and return font style information.
    public var computeStyleInfo: Swift.Bool = Swift.Bool()

    /// Turn on the model that can extract LaTeX math formulas.
    public var enableMathOcr: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `PremiumFeatures`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PremiumFeatures().with { $0.enableSelectionMarkDetection = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.OcrConfig.PremiumFeatures"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.OcrConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
