// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Config for Document OCR.
public struct OcrConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Hints for the OCR model.
  public var hints: OcrConfig.Hints? = nil

  /// Enables special handling for PDFs with existing text information. Results
  /// in better text extraction quality in such PDF inputs.
  public var enableNativePdfParsing: Swift.Bool = Swift.Bool()

  /// Enables intelligent document quality scores after OCR. Can help with
  /// diagnosing why OCR responses are of poor quality for a given input.
  /// Adds additional latency comparable to regular OCR to the process call.
  public var enableImageQualityScores: Swift.Bool = Swift.Bool()

  /// A list of advanced OCR options to further fine-tune OCR behavior. Current
  /// valid values are:
  ///
  /// - `legacy_layout`: a heuristics layout detection algorithm, which serves as
  /// an alternative to the current ML-based layout detection algorithm.
  /// Customers can choose the best suitable layout algorithm based on their
  /// situation.
  public var advancedOcrOptions: [Swift.String] = []

  /// Includes symbol level OCR information if set to true.
  public var enableSymbol: Swift.Bool = Swift.Bool()

  /// Turn on font identification model and return font style information.
  /// Deprecated, use
  /// [PremiumFeatures.compute_style_info][google.cloud.documentai.v1.OcrConfig.PremiumFeatures.compute_style_info]
  /// instead.
  ///
  /// [google.cloud.documentai.v1.OcrConfig.PremiumFeatures.compute_style_info]: <doc:OcrConfig/PremiumFeatures/computeStyleInfo>
  @available(*, deprecated)
  public var computeStyleInfo: Swift.Bool = Swift.Bool()

  /// Turn off character box detector in OCR engine. Character box detection is
  /// enabled by default in OCR 2.0 (and later) processors.
  public var disableCharacterBoxesDetection: Swift.Bool = Swift.Bool()

  /// Configurations for premium OCR features.
  public var premiumFeatures: OcrConfig.PremiumFeatures? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `OcrConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OcrConfig().with { $0.hints = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let hints = CodingKeys(stringValue: "hints")
    static let enableNativePdfParsing = CodingKeys(stringValue: "enableNativePdfParsing")
    static let enableImageQualityScores = CodingKeys(stringValue: "enableImageQualityScores")
    static let advancedOcrOptions = CodingKeys(stringValue: "advancedOcrOptions")
    static let enableSymbol = CodingKeys(stringValue: "enableSymbol")
    static let computeStyleInfo = CodingKeys(stringValue: "computeStyleInfo")
    static let disableCharacterBoxesDetection = CodingKeys(
      stringValue: "disableCharacterBoxesDetection")
    static let premiumFeatures = CodingKeys(stringValue: "premiumFeatures")

    static let _knownKeys: Set<Swift.String> = [
      "hints",
      "enableNativePdfParsing",
      "enableImageQualityScores",
      "advancedOcrOptions",
      "enableSymbol",
      "computeStyleInfo",
      "disableCharacterBoxesDetection",
      "premiumFeatures",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.hints = try container.decodeIfPresent(OcrConfig.Hints.self, forKey: .hints)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableNativePdfParsing) {
      self.enableNativePdfParsing = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableImageQualityScores)
    {
      self.enableImageQualityScores = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .advancedOcrOptions) {
      self.advancedOcrOptions = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableSymbol) {
      self.enableSymbol = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .computeStyleInfo) {
      self.computeStyleInfo = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .disableCharacterBoxesDetection)
    {
      self.disableCharacterBoxesDetection = value
    }
    self.premiumFeatures = try container.decodeIfPresent(
      OcrConfig.PremiumFeatures.self, forKey: .premiumFeatures)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.hints, forKey: .hints)
    try container.encode(self.enableNativePdfParsing, forKey: .enableNativePdfParsing)
    try container.encode(self.enableImageQualityScores, forKey: .enableImageQualityScores)
    try container.encode(self.advancedOcrOptions, forKey: .advancedOcrOptions)
    try container.encode(self.enableSymbol, forKey: .enableSymbol)
    try container.encode(self.computeStyleInfo, forKey: .computeStyleInfo)
    try container.encode(
      self.disableCharacterBoxesDetection, forKey: .disableCharacterBoxesDetection)
    try container.encodeIfPresent(self.premiumFeatures, forKey: .premiumFeatures)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Hints for OCR Engine
  public struct Hints: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// List of BCP-47 language codes to use for OCR. In most cases, not
    /// specifying it yields the best results since it enables automatic language
    /// detection. For languages based on the Latin alphabet, setting hints is
    /// not needed. In rare cases, when the language of the text in the
    /// image is known, setting a hint will help get better results (although it
    /// will be a significant hindrance if the hint is wrong).
    public var languageHints: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Hints`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Hints().with { $0.languageHints = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let languageHints = CodingKeys(stringValue: "languageHints")

      static let _knownKeys: Set<Swift.String> = [
        "languageHints"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .languageHints) {
        self.languageHints = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.languageHints, forKey: .languageHints)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.OcrConfig.Hints"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configurations for premium OCR features.
  public struct PremiumFeatures: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Turn on selection mark detector in OCR engine. Only available in OCR 2.0
    /// (and later) processors.
    public var enableSelectionMarkDetection: Swift.Bool = Swift.Bool()

    /// Turn on font identification model and return font style information.
    public var computeStyleInfo: Swift.Bool = Swift.Bool()

    /// Turn on the model that can extract LaTeX math formulas.
    public var enableMathOcr: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `PremiumFeatures`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PremiumFeatures().with { $0.enableSelectionMarkDetection = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enableSelectionMarkDetection = CodingKeys(
        stringValue: "enableSelectionMarkDetection")
      static let computeStyleInfo = CodingKeys(stringValue: "computeStyleInfo")
      static let enableMathOcr = CodingKeys(stringValue: "enableMathOcr")

      static let _knownKeys: Set<Swift.String> = [
        "enableSelectionMarkDetection",
        "computeStyleInfo",
        "enableMathOcr",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .enableSelectionMarkDetection)
      {
        self.enableSelectionMarkDetection = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .computeStyleInfo) {
        self.computeStyleInfo = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableMathOcr) {
        self.enableMathOcr = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enableSelectionMarkDetection, forKey: .enableSelectionMarkDetection)
      try container.encode(self.computeStyleInfo, forKey: .computeStyleInfo)
      try container.encode(self.enableMathOcr, forKey: .enableMathOcr)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.OcrConfig.PremiumFeatures"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.OcrConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
