// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for the
/// [ProcessDocument][google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]
/// method.
///
/// [google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]: <doc:DocumentProcessorServiceClient/processDocument(request:options:)>
public struct ProcessRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [Processor][google.cloud.documentai.v1.Processor] or
  /// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion]
  /// to use for processing. If a
  /// [Processor][google.cloud.documentai.v1.Processor] is specified, the server
  /// will use its [default
  /// version][google.cloud.documentai.v1.Processor.default_processor_version].
  /// Format: `projects/{project}/locations/{location}/processors/{processor}`,
  /// or
  /// `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`
  ///
  /// [google.cloud.documentai.v1.Processor]: <doc:Processor>
  /// [google.cloud.documentai.v1.Processor.default_processor_version]: <doc:Processor/defaultProcessorVersion>
  /// [google.cloud.documentai.v1.ProcessorVersion]: <doc:ProcessorVersion>
  public var name: Swift.String = Swift.String()

  /// Whether human review should be skipped for this request. Default to
  /// `false`.
  public var skipHumanReview: Swift.Bool = Swift.Bool()

  /// Specifies which fields to include in the
  /// [ProcessResponse.document][google.cloud.documentai.v1.ProcessResponse.document]
  /// output. Only supports top-level document and pages field, so it must be in
  /// the form of `{document_field_name}` or `pages.{page_field_name}`.
  ///
  /// [google.cloud.documentai.v1.ProcessResponse.document]: <doc:ProcessResponse/document>
  public var fieldMask: GoogleCloudWKT.FieldMask? = nil

  /// Inference-time options for the process API
  public var processOptions: ProcessOptions? = nil

  /// Optional. The labels with user-defined metadata for the request.
  ///
  /// Label keys and values can be no longer than 63 characters
  /// (Unicode codepoints) and can only contain lowercase letters, numeric
  /// characters, underscores, and dashes. International characters are allowed.
  /// Label values are optional. Label keys must start with a letter.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Option to remove images from the document.
  public var imagelessMode: Swift.Bool = Swift.Bool()

  /// The document payload.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `ProcessRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProcessRequest().with { $0.inlineDocument = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case inlineDocument = "inlineDocument"
    case rawDocument = "rawDocument"
    case gcsDocument = "gcsDocument"
    case name = "name"
    case skipHumanReview = "skipHumanReview"
    case fieldMask = "fieldMask"
    case processOptions = "processOptions"
    case labels = "labels"
    case imagelessMode = "imagelessMode"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.skipHumanReview = try container.decode(Swift.Bool.self, forKey: .skipHumanReview)
    self.fieldMask = try container.decodeIfPresent(
      GoogleCloudWKT.FieldMask.self, forKey: .fieldMask)
    self.processOptions = try container.decodeIfPresent(
      ProcessOptions.self, forKey: .processOptions)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.imagelessMode = try container.decode(Swift.Bool.self, forKey: .imagelessMode)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let inlineDocument = try container.decodeIfPresent(Document?.self, forKey: .inlineDocument) {
      try sourceCheckAndSet(.inlineDocument(inlineDocument))
    }
    if let rawDocument = try container.decodeIfPresent(RawDocument?.self, forKey: .rawDocument) {
      try sourceCheckAndSet(.rawDocument(rawDocument))
    }
    if let gcsDocument = try container.decodeIfPresent(GcsDocument?.self, forKey: .gcsDocument) {
      try sourceCheckAndSet(.gcsDocument(gcsDocument))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.skipHumanReview, forKey: .skipHumanReview)
    try container.encode(self.fieldMask, forKey: .fieldMask)
    try container.encode(self.processOptions, forKey: .processOptions)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.imagelessMode, forKey: .imagelessMode)

    if let choice = self.source {
      switch choice {
      case .inlineDocument(let value):
        try container.encode(value, forKey: .inlineDocument)
      case .rawDocument(let value):
        try container.encode(value, forKey: .rawDocument)
      case .gcsDocument(let value):
        try container.encode(value, forKey: .gcsDocument)
      }
    }
  }

  /// The document payload.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// An inline document proto.
    indirect case inlineDocument(Document?)
    /// A raw document content (bytes).
    indirect case rawDocument(RawDocument?)
    /// A raw document on Google Cloud Storage.
    indirect case gcsDocument(GcsDocument?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.ProcessRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
