// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A processor version is an implementation of a processor. Each processor
/// can have multiple versions, pretrained by Google internally or uptrained
/// by the customer. A processor can only have one default version at a time.
/// Its document-processing behavior is defined by that version.
public struct ProcessorVersion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the processor version.
  /// Format:
  /// `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processor_version}`
  public var name: Swift.String = Swift.String()

  /// The display name of the processor version.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The schema of the processor version. Describes the output.
  public var documentSchema: DocumentSchema? = nil

  /// Output only. The state of the processor version.
  public var state: ProcessorVersion.State = ProcessorVersion.State()

  /// Output only. The time the processor version was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The most recently invoked evaluation for the processor
  /// version.
  public var latestEvaluation: EvaluationReference? = nil

  /// Output only. The KMS key name used for encryption.
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. The KMS key version with which data is encrypted.
  public var kmsKeyVersionName: Swift.String = Swift.String()

  /// Output only. Denotes that this `ProcessorVersion` is managed by Google.
  public var googleManaged: Swift.Bool = Swift.Bool()

  /// Output only. If set, information about the eventual deprecation of this
  /// version.
  public var deprecationInfo: ProcessorVersion.DeprecationInfo? = nil

  /// Output only. The model type of this processor version.
  public var modelType: ProcessorVersion.ModelType = ProcessorVersion.ModelType()

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Output only. Information about Generative AI model-based processor
  /// versions.
  public var genAiModelInfo: ProcessorVersion.GenAiModelInfo? = nil

  /// Initialize a new instance of `ProcessorVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProcessorVersion().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information about the upcoming deprecation of this processor version.
  public struct DeprecationInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The time at which this processor version will be deprecated.
    public var deprecationTime: GoogleCloudWkt.Timestamp? = nil

    /// If set, the processor version that will be used as a replacement.
    public var replacementProcessorVersion: Swift.String = Swift.String()

    /// Initialize a new instance of `DeprecationInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeprecationInfo().with { $0.deprecationTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.ProcessorVersion.DeprecationInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Information about Generative AI model-based processor versions.
  public struct GenAiModelInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The processor version is either a pretrained Google-managed foundation
    /// model or a custom Generative AI model created by the user.
    public var modelInfo: OneOf_ModelInfo? = nil

    /// Initialize a new instance of `GenAiModelInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GenAiModelInfo().with { $0.foundationGenAiModelInfo = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case foundationGenAiModelInfo = "foundationGenAiModelInfo"
      case customGenAiModelInfo = "customGenAiModelInfo"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var modelInfo: OneOf_ModelInfo? = nil
      let modelInfoCheckAndSet = {
        if modelInfo != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'modelInfo'"))
        }
        modelInfo = $0
      }
      if let foundationGenAiModelInfo = try container.decodeIfPresent(
        ProcessorVersion.GenAiModelInfo.FoundationGenAiModelInfo?.self,
        forKey: .foundationGenAiModelInfo)
      {
        try modelInfoCheckAndSet(.foundationGenAiModelInfo(foundationGenAiModelInfo))
      }
      if let customGenAiModelInfo = try container.decodeIfPresent(
        ProcessorVersion.GenAiModelInfo.CustomGenAiModelInfo?.self, forKey: .customGenAiModelInfo)
      {
        try modelInfoCheckAndSet(.customGenAiModelInfo(customGenAiModelInfo))
      }
      self.modelInfo = modelInfo
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.modelInfo {
        switch choice {
        case .foundationGenAiModelInfo(let value):
          try container.encode(value, forKey: .foundationGenAiModelInfo)
        case .customGenAiModelInfo(let value):
          try container.encode(value, forKey: .customGenAiModelInfo)
        }
      }
    }

    /// Information for a pretrained Google-managed foundation model.
    public struct FoundationGenAiModelInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Whether finetuning is allowed for this base processor version.
      public var finetuningAllowed: Swift.Bool = Swift.Bool()

      /// The minimum number of labeled documents in the training dataset
      /// required for finetuning.
      public var minTrainLabeledDocuments: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `FoundationGenAiModelInfo`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = FoundationGenAiModelInfo().with { $0.finetuningAllowed = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.documentai.v1.ProcessorVersion.GenAiModelInfo.FoundationGenAiModelInfo"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Information for a custom Generative AI model created by the user. These
    /// are created with `Create New Version` in either the `Call foundation
    /// model` or `Fine tuning` tabs.
    public struct CustomGenAiModelInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The type of custom model created by the user.
      public var customModelType:
        ProcessorVersion.GenAiModelInfo.CustomGenAiModelInfo.CustomModelType = ProcessorVersion
          .GenAiModelInfo.CustomGenAiModelInfo.CustomModelType()

      /// The base processor version ID for the custom model.
      public var baseProcessorVersionId: Swift.String = Swift.String()

      /// Initialize a new instance of `CustomGenAiModelInfo`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CustomGenAiModelInfo().with { $0.customModelType = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// The type of custom model created by the user.
      public enum CustomModelType: Codable, Equatable, Sendable {
        /// The model type is unspecified.
        case unspecified
        /// The model is a versioned foundation model.
        case versionedFoundation
        /// The model is a finetuned foundation model.
        case fineTuned
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .versionedFoundation: return 1
          case .fineTuned: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "CUSTOM_MODEL_TYPE_UNSPECIFIED"
          case .versionedFoundation: return "VERSIONED_FOUNDATION"
          case .fineTuned: return "FINE_TUNED"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CustomModelType/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "CUSTOM_MODEL_TYPE_UNSPECIFIED": self = .unspecified
          case "VERSIONED_FOUNDATION": self = .versionedFoundation
          case "FINE_TUNED": self = .fineTuned
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CustomModelType/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .versionedFoundation
          case 2: self = .fineTuned
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .versionedFoundation: return try container.encode(1)
          case .fineTuned: return try container.encode(2)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.documentai.v1.ProcessorVersion.GenAiModelInfo.CustomGenAiModelInfo"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// The processor version is either a pretrained Google-managed foundation
    /// model or a custom Generative AI model created by the user.
    public enum OneOf_ModelInfo: Codable, Equatable, Sendable {
      /// Information for a pretrained Google-managed foundation model.
      indirect case foundationGenAiModelInfo(
        ProcessorVersion.GenAiModelInfo.FoundationGenAiModelInfo?)
      /// Information for a custom Generative AI model created by the user.
      indirect case customGenAiModelInfo(ProcessorVersion.GenAiModelInfo.CustomGenAiModelInfo?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.ProcessorVersion.GenAiModelInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The possible states of the processor version.
  public enum State: Codable, Equatable, Sendable {
    /// The processor version is in an unspecified state.
    case unspecified
    /// The processor version is deployed and can be used for processing.
    case deployed
    /// The processor version is being deployed.
    case deploying
    /// The processor version is not deployed and cannot be used for processing.
    case undeployed
    /// The processor version is being undeployed.
    case undeploying
    /// The processor version is being created.
    case creating
    /// The processor version is being deleted.
    case deleting
    /// The processor version failed and is in an indeterminate state.
    case failed
    /// The processor version is being imported.
    case importing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .deployed: return 1
      case .deploying: return 2
      case .undeployed: return 3
      case .undeploying: return 4
      case .creating: return 5
      case .deleting: return 6
      case .failed: return 7
      case .importing: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .deployed: return "DEPLOYED"
      case .deploying: return "DEPLOYING"
      case .undeployed: return "UNDEPLOYED"
      case .undeploying: return "UNDEPLOYING"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .failed: return "FAILED"
      case .importing: return "IMPORTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "DEPLOYED": self = .deployed
      case "DEPLOYING": self = .deploying
      case "UNDEPLOYED": self = .undeployed
      case "UNDEPLOYING": self = .undeploying
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "FAILED": self = .failed
      case "IMPORTING": self = .importing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .deployed
      case 2: self = .deploying
      case 3: self = .undeployed
      case 4: self = .undeploying
      case 5: self = .creating
      case 6: self = .deleting
      case 7: self = .failed
      case 8: self = .importing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .deployed: return try container.encode(1)
      case .deploying: return try container.encode(2)
      case .undeployed: return try container.encode(3)
      case .undeploying: return try container.encode(4)
      case .creating: return try container.encode(5)
      case .deleting: return try container.encode(6)
      case .failed: return try container.encode(7)
      case .importing: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The possible model types of the processor version.
  public enum ModelType: Codable, Equatable, Sendable {
    /// The processor version has unspecified model type.
    case unspecified
    /// The processor version has generative model type.
    case generative
    /// The processor version has custom model type.
    case custom
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .generative: return 1
      case .custom: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODEL_TYPE_UNSPECIFIED"
      case .generative: return "MODEL_TYPE_GENERATIVE"
      case .custom: return "MODEL_TYPE_CUSTOM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ModelType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODEL_TYPE_UNSPECIFIED": self = .unspecified
      case "MODEL_TYPE_GENERATIVE": self = .generative
      case "MODEL_TYPE_CUSTOM": self = .custom
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ModelType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .generative
      case 2: self = .custom
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .generative: return try container.encode(1)
      case .custom: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.ProcessorVersion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
