// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A processor type is responsible for performing a certain document
/// understanding task on a certain type of document.
public struct ProcessorType: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The resource name of the processor type.
  /// Format: `projects/{project}/processorTypes/{processor_type}`
  public var name: Swift.String = Swift.String()

  /// The processor type, such as: `OCR_PROCESSOR`, `INVOICE_PROCESSOR`.
  public var type: Swift.String = Swift.String()

  /// The processor category, used by UI to group processor types.
  public var category: Swift.String = Swift.String()

  /// The locations in which this processor is available.
  public var availableLocations: [ProcessorType.LocationInfo] = []

  /// Whether the processor type allows creation. If true, users can create a
  /// processor of this processor type. Otherwise, users need to request access.
  public var allowCreation: Swift.Bool = Swift.Bool()

  /// Launch stage of the processor type
  public var launchStage: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// A set of Cloud Storage URIs of sample documents for this processor.
  public var sampleDocumentUris: [Swift.String] = []

  /// Initialize a new instance of `ProcessorType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProcessorType().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The location information about where the processor is available.
  public struct LocationInfo: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The location ID. For supported locations, refer to [regional and
    /// multi-regional support](/document-ai/docs/regions).
    public var locationId: Swift.String = Swift.String()

    /// Initialize a new instance of `LocationInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LocationInfo().with { $0.locationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.ProcessorType.LocationInfo"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.ProcessorType"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
