// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The first-class citizen for Document AI. Each processor defines how to
/// extract structural information from a document.
public struct Processor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Immutable. The resource name of the processor.
  /// Format: `projects/{project}/locations/{location}/processors/{processor}`
  public var name: Swift.String = Swift.String()

  /// The processor type, such as: `OCR_PROCESSOR`, `INVOICE_PROCESSOR`.
  /// To get a list of processor types, see
  /// [FetchProcessorTypes][google.cloud.documentai.v1.DocumentProcessorService.FetchProcessorTypes].
  ///
  /// [google.cloud.documentai.v1.DocumentProcessorService.FetchProcessorTypes]: <doc:DocumentProcessorServiceClient/fetchProcessorTypes(request:options:)>
  public var type: Swift.String = Swift.String()

  /// The display name of the processor.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The state of the processor.
  public var state: Processor.State = Processor.State()

  /// The default processor version.
  public var defaultProcessorVersion: Swift.String = Swift.String()

  /// Output only. The processor version aliases.
  public var processorVersionAliases: [ProcessorVersionAlias] = []

  /// Output only. Immutable. The http endpoint that can be called to invoke
  /// processing.
  public var processEndpoint: Swift.String = Swift.String()

  /// Output only. The time the processor was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// The [KMS key](https://cloud.google.com/security-key-management) used for
  /// encryption and decryption in CMEK scenarios.
  public var kmsKeyName: Swift.String = Swift.String()

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool = Swift.Bool()

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `Processor`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Processor().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The possible states of the processor.
  public enum State: Codable, Equatable, Sendable {
    /// The processor is in an unspecified state.
    case unspecified
    /// The processor is enabled, i.e., has an enabled version which can
    /// currently serve processing requests and all the feature dependencies have
    /// been successfully initialized.
    case enabled
    /// The processor is disabled.
    case disabled
    /// The processor is being enabled, will become `ENABLED` if successful.
    case enabling
    /// The processor is being disabled, will become `DISABLED` if successful.
    case disabling
    /// The processor is being created, will become either `ENABLED` (for
    /// successful creation) or `FAILED` (for failed ones).
    /// Once a processor is in this state, it can then be used for document
    /// processing, but the feature dependencies of the processor might not be
    /// fully created yet.
    case creating
    /// The processor failed during creation or initialization of feature
    /// dependencies. The user should delete the processor and recreate one as
    /// all the functionalities of the processor are disabled.
    case failed
    /// The processor is being deleted, will be removed if successful.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .enabling: return 3
      case .disabling: return 4
      case .creating: return 5
      case .failed: return 6
      case .deleting: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .enabling: return "ENABLING"
      case .disabling: return "DISABLING"
      case .creating: return "CREATING"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "ENABLING": self = .enabling
      case "DISABLING": self = .disabling
      case "CREATING": self = .creating
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      case 3: self = .enabling
      case 4: self = .disabling
      case 5: self = .creating
      case 6: self = .failed
      case 7: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabled: return try container.encode(1)
      case .disabled: return try container.encode(2)
      case .enabling: return try container.encode(3)
      case .disabling: return try container.encode(4)
      case .creating: return try container.encode(5)
      case .failed: return try container.encode(6)
      case .deleting: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.Processor"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
