// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Options for Process API
public struct ProcessOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Only applicable to `OCR_PROCESSOR` and `FORM_PARSER_PROCESSOR`.
  /// Returns error if set on other processor types.
  public var ocrConfig: OcrConfig? = nil

  /// Optional. Only applicable to `LAYOUT_PARSER_PROCESSOR`.
  /// Returns error if set on other processor types.
  public var layoutConfig: ProcessOptions.LayoutConfig? = nil

  /// Optional. Override the schema of the
  /// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion]. Will
  /// return an Invalid Argument error if this field is set when the underlying
  /// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion] doesn't
  /// support schema override.
  ///
  /// [google.cloud.documentai.v1.ProcessorVersion]: <doc:ProcessorVersion>
  public var schemaOverride: DocumentSchema? = nil

  /// A subset of pages to process. If not specified, all pages are processed.
  /// If a page range is set, only the given pages are extracted and processed
  /// from the document. In the output document,
  /// [Document.Page.page_number][google.cloud.documentai.v1.Document.Page.page_number]
  /// refers to the page number in the original document.
  /// This configuration only applies to online processing with
  /// [ProcessDocument][google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument].
  ///
  /// [google.cloud.documentai.v1.Document.Page.page_number]: <doc:Document/Page/pageNumber>
  /// [google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]: <doc:DocumentProcessorServiceClient/processDocument(request:options:)>
  public var pageRange: OneOf_PageRange? = nil

  /// Initialize a new instance of `ProcessOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProcessOptions().with { $0.individualPageSelector = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case individualPageSelector = "individualPageSelector"
    case fromStart = "fromStart"
    case fromEnd = "fromEnd"
    case ocrConfig = "ocrConfig"
    case layoutConfig = "layoutConfig"
    case schemaOverride = "schemaOverride"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.ocrConfig = try container.decodeIfPresent(OcrConfig.self, forKey: .ocrConfig)
    self.layoutConfig = try container.decodeIfPresent(
      ProcessOptions.LayoutConfig.self, forKey: .layoutConfig)
    self.schemaOverride = try container.decodeIfPresent(
      DocumentSchema.self, forKey: .schemaOverride)

    var pageRange: OneOf_PageRange? = nil
    let pageRangeCheckAndSet = {
      if pageRange != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'pageRange'"))
      }
      pageRange = $0
    }
    if let individualPageSelector = try container.decodeIfPresent(
      ProcessOptions.IndividualPageSelector?.self, forKey: .individualPageSelector)
    {
      try pageRangeCheckAndSet(.individualPageSelector(individualPageSelector))
    }
    if let fromStart = try container.decodeIfPresent(Swift.Int32.self, forKey: .fromStart) {
      try pageRangeCheckAndSet(.fromStart(fromStart))
    }
    if let fromEnd = try container.decodeIfPresent(Swift.Int32.self, forKey: .fromEnd) {
      try pageRangeCheckAndSet(.fromEnd(fromEnd))
    }
    self.pageRange = pageRange
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.ocrConfig, forKey: .ocrConfig)
    try container.encode(self.layoutConfig, forKey: .layoutConfig)
    try container.encode(self.schemaOverride, forKey: .schemaOverride)

    if let choice = self.pageRange {
      switch choice {
      case .individualPageSelector(let value):
        try container.encode(value, forKey: .individualPageSelector)
      case .fromStart(let value):
        try container.encode(value, forKey: .fromStart)
      case .fromEnd(let value):
        try container.encode(value, forKey: .fromEnd)
      }
    }
  }

  /// Serving config for layout parser processor.
  public struct LayoutConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Config for chunking in layout parser processor.
    public var chunkingConfig: ProcessOptions.LayoutConfig.ChunkingConfig? = nil

    /// Optional. Whether to include images in layout parser processor response.
    public var returnImages: Swift.Bool = Swift.Bool()

    /// Optional. Whether to include bounding boxes in layout parser processor
    /// response.
    public var returnBoundingBoxes: Swift.Bool = Swift.Bool()

    /// Optional. Whether to include image annotations in layout parser response.
    public var enableImageAnnotation: Swift.Bool = Swift.Bool()

    /// Optional. Whether to include table annotations in layout parser response.
    public var enableTableAnnotation: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `LayoutConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LayoutConfig().with { $0.chunkingConfig = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Serving config for chunking.
    public struct ChunkingConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. The chunk sizes to use when splitting documents, in order of
      /// level.
      public var chunkSize: Swift.Int32 = Swift.Int32()

      /// Optional. Whether or not to include ancestor headings when splitting.
      public var includeAncestorHeadings: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `ChunkingConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ChunkingConfig().with { $0.chunkSize = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.documentai.v1.ProcessOptions.LayoutConfig.ChunkingConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.ProcessOptions.LayoutConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A list of individual page numbers.
  public struct IndividualPageSelector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Indices of the pages (starting from 1).
    public var pages: [Swift.Int32] = []

    /// Initialize a new instance of `IndividualPageSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IndividualPageSelector().with { $0.pages = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.ProcessOptions.IndividualPageSelector"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A subset of pages to process. If not specified, all pages are processed.
  /// If a page range is set, only the given pages are extracted and processed
  /// from the document. In the output document,
  /// [Document.Page.page_number][google.cloud.documentai.v1.Document.Page.page_number]
  /// refers to the page number in the original document.
  /// This configuration only applies to online processing with
  /// [ProcessDocument][google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument].
  ///
  /// [google.cloud.documentai.v1.Document.Page.page_number]: <doc:Document/Page/pageNumber>
  /// [google.cloud.documentai.v1.DocumentProcessorService.ProcessDocument]: <doc:DocumentProcessorServiceClient/processDocument(request:options:)>
  public enum OneOf_PageRange: Codable, Equatable, Sendable {
    /// Which pages to process (1-indexed).
    indirect case individualPageSelector(ProcessOptions.IndividualPageSelector?)
    /// Only process certain pages from the start. Process all if the document
    /// has fewer pages.
    case fromStart(Swift.Int32)
    /// Only process certain pages from the end, same as above.
    case fromEnd(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.ProcessOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
