// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleApi
@_spi(GoogleCloudInternal) import GoogleWKT

/// A processor type is responsible for performing a certain document
/// understanding task on a certain type of document.
public struct ProcessorType: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the processor type.
  /// Format: `projects/{project}/processorTypes/{processor_type}`
  public var name: Swift.String = Swift.String()

  /// The processor type, such as: `OCR_PROCESSOR`, `INVOICE_PROCESSOR`.
  public var type: Swift.String = Swift.String()

  /// The processor category, used by UI to group processor types.
  public var category: Swift.String = Swift.String()

  /// The locations in which this processor is available.
  public var availableLocations: [ProcessorType.LocationInfo] = []

  /// Whether the processor type allows creation. If true, users can create a
  /// processor of this processor type. Otherwise, users need to request access.
  public var allowCreation: Swift.Bool = Swift.Bool()

  /// Launch stage of the processor type
  public var launchStage: GoogleApi.LaunchStage = GoogleApi.LaunchStage()

  /// A set of Cloud Storage URIs of sample documents for this processor.
  public var sampleDocumentUris: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ProcessorType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ProcessorType().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let type = CodingKeys(stringValue: "type")
    static let category = CodingKeys(stringValue: "category")
    static let availableLocations = CodingKeys(stringValue: "availableLocations")
    static let allowCreation = CodingKeys(stringValue: "allowCreation")
    static let launchStage = CodingKeys(stringValue: "launchStage")
    static let sampleDocumentUris = CodingKeys(stringValue: "sampleDocumentUris")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "type",
      "category",
      "availableLocations",
      "allowCreation",
      "launchStage",
      "sampleDocumentUris",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .category) {
      self.category = value
    }
    if let value = try container.decodeIfPresent(
      [ProcessorType.LocationInfo].self, forKey: .availableLocations)
    {
      self.availableLocations = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowCreation) {
      self.allowCreation = value
    }
    if let value = try container.decodeIfPresent(GoogleApi.LaunchStage.self, forKey: .launchStage) {
      self.launchStage = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .sampleDocumentUris) {
      self.sampleDocumentUris = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.category, forKey: .category)
    try container.encode(self.availableLocations, forKey: .availableLocations)
    try container.encode(self.allowCreation, forKey: .allowCreation)
    try container.encode(self.launchStage, forKey: .launchStage)
    try container.encode(self.sampleDocumentUris, forKey: .sampleDocumentUris)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The location information about where the processor is available.
  public struct LocationInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The location ID. For supported locations, refer to [regional and
    /// multi-regional support](/document-ai/docs/regions).
    public var locationId: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LocationInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LocationInfo().with { $0.locationId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let locationId = CodingKeys(stringValue: "locationId")

      static let _knownKeys: Set<Swift.String> = [
        "locationId"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationId) {
        self.locationId = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.locationId, forKey: .locationId)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.ProcessorType.LocationInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.ProcessorType"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
