// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Payload message of raw document content (bytes).
public struct RawDocument: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Inline document content.
  public var content: Foundation.Data = Foundation.Data()

  /// An IANA MIME type (RFC6838) indicating the nature and format of the
  /// [content][google.cloud.documentai.v1.RawDocument.content].
  ///
  /// [google.cloud.documentai.v1.RawDocument.content]: <doc:RawDocument/content>
  public var mimeType: Swift.String = Swift.String()

  /// The display name of the document, it supports all Unicode characters except
  /// the following:
  /// `*`, `?`, `[`, `]`, `%`, `{`, `}`,`'`, `\"`, `,`
  /// `~`, `=` and `:` are reserved.
  /// If not specified, a default ID is generated.
  public var displayName: Swift.String = Swift.String()

  /// Initialize a new instance of `RawDocument`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RawDocument().with { $0.content = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.RawDocument"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
