// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for the
/// [ReviewDocument][google.cloud.documentai.v1.DocumentProcessorService.ReviewDocument]
/// method.
///
/// [google.cloud.documentai.v1.DocumentProcessorService.ReviewDocument]: <doc:DocumentProcessorServiceClient/reviewDocument(request:options:)>
public struct ReviewDocumentRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [HumanReviewConfig][google.cloud.documentai.v1.HumanReviewConfig] that the
  /// document will be reviewed with.
  public var humanReviewConfig: Swift.String = Swift.String()

  /// Whether the validation should be performed on the ad-hoc review request.
  public var enableSchemaValidation: Swift.Bool = Swift.Bool()

  /// The priority of the human review task.
  public var priority: ReviewDocumentRequest.Priority = ReviewDocumentRequest.Priority()

  /// The document schema of the human review task.
  public var documentSchema: DocumentSchema? = nil

  /// The document payload.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `ReviewDocumentRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReviewDocumentRequest().with { $0.inlineDocument = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case inlineDocument = "inlineDocument"
    case humanReviewConfig = "humanReviewConfig"
    case enableSchemaValidation = "enableSchemaValidation"
    case priority = "priority"
    case documentSchema = "documentSchema"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.humanReviewConfig = try container.decode(Swift.String.self, forKey: .humanReviewConfig)
    self.enableSchemaValidation = try container.decode(
      Swift.Bool.self, forKey: .enableSchemaValidation)
    self.priority = try container.decode(ReviewDocumentRequest.Priority.self, forKey: .priority)
    self.documentSchema = try container.decodeIfPresent(
      DocumentSchema.self, forKey: .documentSchema)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let inlineDocument = try container.decodeIfPresent(Document?.self, forKey: .inlineDocument) {
      try sourceCheckAndSet(.inlineDocument(inlineDocument))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.humanReviewConfig, forKey: .humanReviewConfig)
    try container.encode(self.enableSchemaValidation, forKey: .enableSchemaValidation)
    try container.encode(self.priority, forKey: .priority)
    try container.encode(self.documentSchema, forKey: .documentSchema)

    if let choice = self.source {
      switch choice {
      case .inlineDocument(let value):
        try container.encode(value, forKey: .inlineDocument)
      }
    }
  }

  /// The priority level of the human review task.
  public enum Priority: Codable, Equatable, Sendable {
    /// The default priority level.
    case `default`
    /// The urgent priority level. The labeling manager should allocate labeler
    /// resource to the urgent task queue to respect this priority level.
    case urgent
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .`default`
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .`default`: return 0
      case .urgent: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .`default`: return "DEFAULT"
      case .urgent: return "URGENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Priority/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEFAULT": self = .`default`
      case "URGENT": self = .urgent
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Priority/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .`default`
      case 1: self = .urgent
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .`default`: return try container.encode(0)
      case .urgent: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The document payload.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// An inline document proto.
    indirect case inlineDocument(Document?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.ReviewDocumentRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
