// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for the
/// [TrainProcessorVersion][google.cloud.documentai.v1.DocumentProcessorService.TrainProcessorVersion]
/// method.
///
/// [google.cloud.documentai.v1.DocumentProcessorService.TrainProcessorVersion]: <doc:DocumentProcessorServiceClient/trainProcessorVersion(request:options:)>
public struct TrainProcessorVersionRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent (project, location and processor) to create the new
  /// version for. Format:
  /// `projects/{project}/locations/{location}/processors/{processor}`.
  public var parent: Swift.String = Swift.String()

  /// Required. The processor version to be created.
  public var processorVersion: ProcessorVersion? = nil

  /// Optional. The schema the processor version will be trained with.
  public var documentSchema: DocumentSchema? = nil

  /// Optional. The input data used to train the
  /// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion].
  ///
  /// [google.cloud.documentai.v1.ProcessorVersion]: <doc:ProcessorVersion>
  public var inputData: TrainProcessorVersionRequest.InputData? = nil

  /// Optional. The processor version to use as a base for training. This
  /// processor version must be a child of `parent`. Format:
  /// `projects/{project}/locations/{location}/processors/{processor}/processorVersions/{processorVersion}`.
  public var baseProcessorVersion: Swift.String = Swift.String()

  public var processorFlags: OneOf_ProcessorFlags? = nil

  /// Initialize a new instance of `TrainProcessorVersionRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TrainProcessorVersionRequest().with { $0.customDocumentExtractionOptions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case customDocumentExtractionOptions = "customDocumentExtractionOptions"
    case foundationModelTuningOptions = "foundationModelTuningOptions"
    case parent = "parent"
    case processorVersion = "processorVersion"
    case documentSchema = "documentSchema"
    case inputData = "inputData"
    case baseProcessorVersion = "baseProcessorVersion"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.processorVersion = try container.decodeIfPresent(
      ProcessorVersion.self, forKey: .processorVersion)
    self.documentSchema = try container.decodeIfPresent(
      DocumentSchema.self, forKey: .documentSchema)
    self.inputData = try container.decodeIfPresent(
      TrainProcessorVersionRequest.InputData.self, forKey: .inputData)
    self.baseProcessorVersion = try container.decode(
      Swift.String.self, forKey: .baseProcessorVersion)

    var processorFlags: OneOf_ProcessorFlags? = nil
    let processorFlagsCheckAndSet = {
      if processorFlags != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'processorFlags'"))
      }
      processorFlags = $0
    }
    if let customDocumentExtractionOptions = try container.decodeIfPresent(
      TrainProcessorVersionRequest.CustomDocumentExtractionOptions?.self,
      forKey: .customDocumentExtractionOptions)
    {
      try processorFlagsCheckAndSet(
        .customDocumentExtractionOptions(customDocumentExtractionOptions))
    }
    if let foundationModelTuningOptions = try container.decodeIfPresent(
      TrainProcessorVersionRequest.FoundationModelTuningOptions?.self,
      forKey: .foundationModelTuningOptions)
    {
      try processorFlagsCheckAndSet(.foundationModelTuningOptions(foundationModelTuningOptions))
    }
    self.processorFlags = processorFlags
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.processorVersion, forKey: .processorVersion)
    try container.encode(self.documentSchema, forKey: .documentSchema)
    try container.encode(self.inputData, forKey: .inputData)
    try container.encode(self.baseProcessorVersion, forKey: .baseProcessorVersion)

    if let choice = self.processorFlags {
      switch choice {
      case .customDocumentExtractionOptions(let value):
        try container.encode(value, forKey: .customDocumentExtractionOptions)
      case .foundationModelTuningOptions(let value):
        try container.encode(value, forKey: .foundationModelTuningOptions)
      }
    }
  }

  /// The input data used to train a new
  /// [ProcessorVersion][google.cloud.documentai.v1.ProcessorVersion].
  ///
  /// [google.cloud.documentai.v1.ProcessorVersion]: <doc:ProcessorVersion>
  public struct InputData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The documents used for training the new version.
    public var trainingDocuments: BatchDocumentsInputConfig? = nil

    /// The documents used for testing the trained version.
    public var testDocuments: BatchDocumentsInputConfig? = nil

    /// Initialize a new instance of `InputData`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = InputData().with { $0.trainingDocuments = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.documentai.v1.TrainProcessorVersionRequest.InputData"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Options to control the training of the Custom Document Extraction (CDE)
  /// Processor.
  public struct CustomDocumentExtractionOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Training method to use for CDE training.
    public var trainingMethod:
      TrainProcessorVersionRequest.CustomDocumentExtractionOptions.TrainingMethod =
        TrainProcessorVersionRequest.CustomDocumentExtractionOptions.TrainingMethod()

    /// Initialize a new instance of `CustomDocumentExtractionOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomDocumentExtractionOptions().with { $0.trainingMethod = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Training Method for CDE. `TRAINING_METHOD_UNSPECIFIED` will fall back to
    /// `MODEL_BASED`.
    public enum TrainingMethod: Codable, Equatable, Sendable {
      case unspecified
      case modelBased
      case templateBased
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .modelBased: return 1
        case .templateBased: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TRAINING_METHOD_UNSPECIFIED"
        case .modelBased: return "MODEL_BASED"
        case .templateBased: return "TEMPLATE_BASED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TrainingMethod/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TRAINING_METHOD_UNSPECIFIED": self = .unspecified
        case "MODEL_BASED": self = .modelBased
        case "TEMPLATE_BASED": self = .templateBased
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TrainingMethod/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .modelBased
        case 2: self = .templateBased
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .modelBased: return try container.encode(1)
        case .templateBased: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.documentai.v1.TrainProcessorVersionRequest.CustomDocumentExtractionOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Options to control foundation model tuning of the processor.
  public struct FoundationModelTuningOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The number of steps to run for model tuning. Valid values are
    /// between 1 and 400. If not provided, recommended steps will be used.
    public var trainSteps: Swift.Int32 = Swift.Int32()

    /// Optional. The multiplier to apply to the recommended learning rate. Valid
    /// values are between 0.1 and 10. If not provided, recommended learning rate
    /// will be used.
    public var learningRateMultiplier: Swift.Float = Swift.Float()

    /// Initialize a new instance of `FoundationModelTuningOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FoundationModelTuningOptions().with { $0.trainSteps = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.documentai.v1.TrainProcessorVersionRequest.FoundationModelTuningOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_ProcessorFlags: Codable, Equatable, Sendable {
    /// Options to control Custom Document Extraction (CDE) Processor.
    indirect case customDocumentExtractionOptions(
      TrainProcessorVersionRequest.CustomDocumentExtractionOptions?)
    /// Options to control foundation model tuning of a processor.
    indirect case foundationModelTuningOptions(
      TrainProcessorVersionRequest.FoundationModelTuningOptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.TrainProcessorVersionRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
