// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// The metadata that represents a processor version being created.
public struct TrainProcessorVersionMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The basic metadata of the long-running operation.
  public var commonMetadata: CommonOperationMetadata? = nil

  /// The training dataset validation information.
  public var trainingDatasetValidation: TrainProcessorVersionMetadata.DatasetValidation? = nil

  /// The test dataset validation information.
  public var testDatasetValidation: TrainProcessorVersionMetadata.DatasetValidation? = nil

  /// Initialize a new instance of `TrainProcessorVersionMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TrainProcessorVersionMetadata().with { $0.commonMetadata = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The dataset validation information.
  /// This includes any and all errors with documents and the dataset.
  public struct DatasetValidation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The total number of document errors.
    public var documentErrorCount: Swift.Int32 = Swift.Int32()

    /// The total number of dataset errors.
    public var datasetErrorCount: Swift.Int32 = Swift.Int32()

    /// Error information pertaining to specific documents. A maximum of 10
    /// document errors will be returned.
    /// Any document with errors will not be used throughout training.
    public var documentErrors: [GoogleRpc.Status] = []

    /// Error information for the dataset as a whole. A maximum of 10 dataset
    /// errors will be returned.
    /// A single dataset error is terminal for training.
    public var datasetErrors: [GoogleRpc.Status] = []

    /// Initialize a new instance of `DatasetValidation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DatasetValidation().with { $0.documentErrorCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.documentai.v1.TrainProcessorVersionMetadata.DatasetValidation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.documentai.v1.TrainProcessorVersionMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
